import { existsSync, promises as fs } from "fs"
import path from "path"
import { Config } from "@/src/utils/get-config"
import { highlighter } from "@/src/utils/highlighter"
import { logger } from "@/src/utils/logger"
import { spinner } from "@/src/utils/spinner"

/**
 * Scaffolds the CSS entry a consumer of the `import` distribution path
 * needs for `@marko-ui/shadcn` (see notes/plans/dual-distribution-plan.md §1
 * and notes/css-architecture.md "The mu-* hooks"). Unlike `updateCss`
 * (postcss object transform, used by the copy path to inject registry item
 * `css`/`cssVars`), this writes literal `@import`/`@custom-variant`
 * statements — there is no registry item driving it, just a fixed template.
 *
 * Two requirements are silent-failure traps if missed (spike-3a-verdict.md):
 *   - the style layer MUST be imported with `layer(components)`, or a
 *     consumer's own utility classes silently lose to it regardless of
 *     specificity;
 *   - the `@custom-variant style-<name>` bridge MUST be defined, or
 *     `data-open:`-style variant classes parse fine and emit nothing.
 */
export async function scaffoldImportDistributionCss(
  config: Config,
  options: {
    baseColor: string
    visualStyle: string
    silent?: boolean
  }
) {
  const cssFilepath = config.resolvedPaths.tailwindCss
  if (!cssFilepath) {
    return
  }

  const cssSpinner = spinner(
    `Writing ${highlighter.info(
      path.relative(config.resolvedPaths.cwd, cssFilepath)
    )} for the import distribution.`,
    { silent: options.silent }
  ).start()

  const globalsFile =
    options.baseColor === "neutral"
      ? "globals.css"
      : `globals-${options.baseColor}.css`

  let output = ""
  if (existsSync(cssFilepath)) {
    output = await fs.readFile(cssFilepath, "utf8")
  } else {
    await fs.mkdir(path.dirname(cssFilepath), { recursive: true })
  }

  if (output.includes(IMPORT_DISTRIBUTION_MARKER)) {
    cssSpinner.info(
      `${highlighter.info(
        path.relative(config.resolvedPaths.cwd, cssFilepath)
      )} already has a marko-ui import block. Leaving it as-is.`
    )
    return
  }

  // Avoid a duplicate `@import "tailwindcss";` when the file already has one
  // (e.g. a fresh Marko app's default CSS entry).
  const needsTailwindImport = !/@import\s+["']tailwindcss["']/.test(output)
  const block = buildImportDistributionBlock(globalsFile, options.visualStyle, {
    includeTailwindImport: needsTailwindImport,
  })

  const separator = output.trim().length ? "\n\n" : ""
  await fs.writeFile(cssFilepath, output.trimEnd() + separator + block, "utf8")

  cssSpinner.succeed()
}

const IMPORT_DISTRIBUTION_MARKER = "marko-ui:import-distribution"

function buildImportDistributionBlock(
  globalsFile: string,
  visualStyle: string,
  options: { includeTailwindImport: boolean }
) {
  const tailwindImport = options.includeTailwindImport
    ? `@import "tailwindcss";\n`
    : ""
  return `/* ${IMPORT_DISTRIBUTION_MARKER} — generated by \`marko-ui init\`. */
${tailwindImport}@import "@marko-ui/shadcn/styles/${globalsFile}";
@import "@marko-ui/shadcn/styles/style-${visualStyle}.css" layer(components);

/* Required so data-open:/data-state-*: variant classes on mu-* components
   compile to real CSS instead of silently emitting nothing. */
@custom-variant style-${visualStyle} (&:where(.style-${visualStyle} *));
`
}
