# syntax=docker/dockerfile:1

# SUPERSEDED — this image no longer builds, and is kept only as a record of
# the Coolify deployment it served.
#
# apps/docs now deploys to Cloudflare as a Worker with static assets
# (see DEPLOY.md). Its build uses @marko/run-adapter-static, which prerenders
# every page and then DELETES the Node server entry this image's CMD runs, so
# `bun dist/index.mjs` below has nothing to execute. Restoring a Node
# deployment would mean removing the adapter from apps/docs/vite.config.ts
# first; it is not a matter of rebuilding this file.
#
# Original description: builds and serves the docs app (apps/docs), which also
# hosts the marko-ui registry as static JSON under /r/* (apps/docs/public/r,
# generated by tooling/build-registry.ts — see .gitignore, it is never
# committed). One image, one deployment, covers both.

ARG BUN_VERSION=1.3.11
ARG REGISTRY_BASE_URL=https://marko-ui.saulo.tech/r

FROM oven/bun:${BUN_VERSION} AS base
WORKDIR /app

# ---- deps: install once, workspace-aware -----------------------------------
FROM base AS deps
COPY package.json bun.lock ./
COPY apps/docs/package.json apps/docs/package.json
COPY packages/shadcn/package.json packages/shadcn/package.json
COPY packages/marko-ui/package.json packages/marko-ui/package.json
COPY tooling/parity/harnesses/marko-ui/package.json tooling/parity/harnesses/marko-ui/package.json
RUN bun install --frozen-lockfile

# ---- build: registry JSON + docs production bundle --------------------------
FROM base AS build
ARG REGISTRY_BASE_URL
COPY --from=deps /app/node_modules ./node_modules
COPY --from=deps /app/apps/docs/node_modules ./apps/docs/node_modules
COPY --from=deps /app/packages/shadcn/node_modules ./packages/shadcn/node_modules
COPY . .

RUN REGISTRY_BASE_URL=${REGISTRY_BASE_URL} bun tooling/build-registry.ts
RUN bun run --cwd apps/docs build

# ---- runtime: slim, production deps only ------------------------------------
# @marko/run's default node adapter build (dist/index.mjs) is NOT a fully
# self-contained bundle: it still imports "marko", "@zag-js/*", "valibot",
# "compression", "serve-static" etc. from node_modules at runtime (verified
# by running dist/index.mjs in isolation — it throws ERR_MODULE_NOT_FOUND
# for "marko" without them). So the runtime stage needs a real
# node_modules, just production-only and workspace-filtered to keep it slim.
FROM base AS runtime
WORKDIR /app
ENV NODE_ENV=production

COPY package.json bun.lock ./
COPY apps/docs/package.json apps/docs/package.json
COPY packages/shadcn/package.json packages/shadcn/package.json
COPY packages/marko-ui/package.json packages/marko-ui/package.json
COPY tooling/parity/harnesses/marko-ui/package.json tooling/parity/harnesses/marko-ui/package.json
RUN bun install --frozen-lockfile --production

COPY --from=build /app/apps/docs/dist ./apps/docs/dist

ENV PORT=3000
EXPOSE 3000

WORKDIR /app/apps/docs
CMD ["bun", "dist/index.mjs"]
