import { existsSync } from "fs"
import path from "path"
import { InvalidConfigIconLibraryError } from "@/src/registry/errors"
import type { RegistryItem } from "@/src/schema"

// Icon libraries the registry's Icon component ships maps for. Mirrors
// upstream shadcn's `iconLibraries` (packages/shadcn/src/icons/libraries.ts)
// and packages/shadcn/ui/icon/icon-names.ts. `ident` is the export name of the
// generated `__<library>__.ts` map.
export const ICON_LIBRARIES = {
  lucide: { ident: "lucideIcons", nodes: false },
  tabler: { ident: "tablerIcons", nodes: false },
  phosphor: { ident: "phosphorIcons", nodes: false },
  remixicon: { ident: "remixiconIcons", nodes: false },
  hugeicons: { ident: "hugeiconsIcons", nodes: true },
} as const

export type IconLibraryName = keyof typeof ICON_LIBRARIES

export function isIconLibraryName(value: unknown): value is IconLibraryName {
  return typeof value === "string" && Object.hasOwn(ICON_LIBRARIES, value)
}

type RegistryFile = NonNullable<RegistryItem["files"]>[number]

const ICON_DIR = /(^|\/)ui\/icon\//
// Derived from ICON_LIBRARIES so a newly added library is recognised as a map
// file automatically instead of falling through as "some other icon file".
const MAP_FILE = new RegExp(
  `(^|/)ui/icon/__(${Object.keys(ICON_LIBRARIES).join("|")})__\\.ts$`
)
const RESOLVE_FILE = /(^|\/)ui\/icon\/resolve\.ts$/
// Files that only exist for our docs site's runtime library switcher / for
// regenerating the maps. Neither is imported by icon.marko, and both name every
// library, so a project with one fixed library has no use for them.
const OMITTED_FILES = /(^|\/)ui\/icon\/(client-swap\.ts|icon-mapping\.json)$/

// Legacy upstream value (see shadcn's legacy-icon-libraries.ts). Upstream's
// add-time transform leaves files untouched for it; so do we.
const LEGACY_ICON_LIBRARIES = new Set(["radix"])

export function isIconResolverPath(filePath: string) {
  return RESOLVE_FILE.test(filePath.split(path.sep).join("/"))
}

/**
 * Maps of OTHER known libraries sitting next to a copied resolver, e.g. left
 * behind by an earlier `add` under a different `iconLibrary`. Only the exact
 * `__<known library>__.ts` names in `iconDir` are returned.
 */
export function findStaleIconMaps(
  iconDir: string,
  iconLibrary: IconLibraryName
): string[] {
  return (Object.keys(ICON_LIBRARIES) as IconLibraryName[])
    .filter((lib) => lib !== iconLibrary)
    .map((lib) => path.join(iconDir, `__${lib}__.ts`))
    .filter((file) => existsSync(file))
}

/**
 * The single-library replacement for the registry's `ui/icon/resolve.ts`.
 * The registry version statically imports all five maps; this one imports only
 * `library`'s, so the consumer's bundle carries one library and `<Icon>` renders
 * synchronously on server and client. Export signatures must match the registry
 * resolve.ts (resolveIconLibrary, resolveIconInner).
 */
export function renderIconResolver(library: IconLibraryName): string {
  const { ident, nodes } = ICON_LIBRARIES[library]
  const render = nodes
    ? `  const nodes = withSuffixFallback(${ident}, name);
  return nodes ? renderHugeiconsNodes(nodes) : FALLBACK_INNER;`
    : `  return withSuffixFallback(${ident}, name) ?? FALLBACK_INNER;`
  const renderImports = nodes
    ? "FALLBACK_INNER, renderHugeiconsNodes, withSuffixFallback"
    : "FALLBACK_INNER, withSuffixFallback"

  return `// Generated by \`marko-ui add\` from components.json \`iconLibrary\`: "${library}".
// Only that library's icon map is imported, so it is the only one bundled.
// To switch libraries, change \`iconLibrary\` and re-run \`marko-ui add icon --overwrite\`.
import { ${ident} } from "./__${library}__.ts";
import type { IconLibraryName } from "./icon-names.ts";
import { ${renderImports} } from "./render.ts";

// This project renders every icon from "${library}" regardless of the
// \`library\` prop.
export function resolveIconLibrary(_requested?: string): IconLibraryName {
  return "${library}";
}

export function resolveIconInner(name: string, _library?: IconLibraryName): string {
${render}
}
`
}

/**
 * Add-time icon handling, the marko-ui counterpart of upstream shadcn's
 * `transformIcons` (utils/transformers/transform-icons.ts). Upstream rewrites
 * `<IconPlaceholder lucide=".." tabler=".."/>` JSX to the configured library's
 * component; our Icon resolves abstract names through generated data maps, so
 * the equivalent is to keep only the configured library's map and swap in a
 * resolver that imports just that map.
 *
 * Like upstream, an unset `iconLibrary` or the legacy `radix` is left alone and
 * the files pass through unchanged. Unlike upstream (which silently ignores any
 * unknown value), a non-empty unknown value throws when the icon files are being
 * added, rather than silently shipping all five libraries.
 */
export function applyIconLibrary(
  files: RegistryItem["files"],
  iconLibrary: string | undefined
): RegistryItem["files"] {
  if (!files?.length || !iconLibrary || LEGACY_ICON_LIBRARIES.has(iconLibrary)) {
    return files
  }
  if (!isIconLibraryName(iconLibrary)) {
    if (files.some((file) => ICON_DIR.test(file.path))) {
      throw new InvalidConfigIconLibraryError(
        iconLibrary,
        Object.keys(ICON_LIBRARIES)
      )
    }
    return files
  }

  const out: RegistryFile[] = []
  for (const file of files) {
    if (!ICON_DIR.test(file.path)) {
      out.push(file)
      continue
    }
    if (OMITTED_FILES.test(file.path)) {
      continue
    }
    const map = MAP_FILE.exec(file.path)
    if (map) {
      if (map[2] === iconLibrary) {
        out.push(file)
      }
      continue
    }
    if (RESOLVE_FILE.test(file.path)) {
      out.push({ ...file, content: renderIconResolver(iconLibrary) })
      continue
    }
    out.push(file)
  }
  return out
}
