export const combobox = {
  value: "sr-only",
  control: "mu-combobox-input w-auto border-input relative flex items-center rounded-md border shadow-xs focus-within:border-ring focus-within:ring-[3px] focus-within:ring-ring/50",
  chips: "mu-combobox-chips flex flex-wrap items-center gap-1 p-1",
  chip: "mu-combobox-chip has-disabled:pointer-events-none has-disabled:cursor-not-allowed has-disabled:opacity-50",
  chipRemove: "mu-combobox-chip-remove",
  chipRemoveIcon: "mu-combobox-chip-indicator-icon pointer-events-none size-3",
  chipInput: "mu-combobox-chip-input min-w-16 flex-1 bg-transparent px-1 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50",
  input: "h-9 flex-1 bg-transparent px-3 text-sm outline-none placeholder:text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50",
  clear: "mu-combobox-clear group-has-data-[slot=combobox-clear]/input-group:hidden data-pressed:bg-transparent flex h-9 w-9 items-center justify-center text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50",
  clearIcon: "mu-combobox-clear-icon pointer-events-none size-4",
  trigger: "mu-combobox-trigger flex h-9 w-9 items-center justify-center text-muted-foreground disabled:cursor-not-allowed disabled:opacity-50",
  triggerIcon: "mu-combobox-trigger-icon pointer-events-none size-4 opacity-50",
  positioner: "isolate z-50",
  content: "mu-combobox-content mu-combobox-content-logical mu-menu-target mu-menu-translucent group/combobox-content relative max-h-(--available-height) w-(--reference-width) max-w-(--available-width) origin-(--transform-origin) overflow-x-hidden overflow-y-auto data-[state=open]:animate-in data-[state=open]:fade-in-0 data-[state=open]:zoom-in-95 data-[state=closed]:animate-out data-[state=closed]:fade-out-0 data-[state=closed]:zoom-out-95",
  list: "mu-combobox-list overflow-y-auto overscroll-contain",
  group: "mu-combobox-group",
  label: "mu-combobox-label",
  item: "mu-combobox-item relative flex w-full cursor-default items-center outline-hidden select-none data-[disabled]:pointer-events-none data-[disabled]:opacity-50 [&_svg]:pointer-events-none [&_svg]:shrink-0",
  itemIndicator: "mu-combobox-item-indicator",
  itemIndicatorIcon: "mu-combobox-item-indicator-icon pointer-events-none size-4",
  separator: "mu-combobox-separator",
  empty: "mu-combobox-empty text-muted-foreground py-1.5 px-2 text-sm",
} as const;
