// Hand-authored prose + example ordering for /docs/components/scroll-area.
// The route pairs each `examples[].name` with the .marko file of the same
// name in this directory; the generated demos-manifest.ts is what actually
// resolves the component and its source text.
import type { ComponentDocs } from "../docs-types.ts";

export const docs: ComponentDocs = {
  description: "Augments native scroll functionality for custom, cross-browser styling.",
  // Tags are registered by the taglib (package install or `marko-ui
  // init`), so no import is required. The explicit-import form is
  // documented as the override/escape hatch.
  usageTags: `<ScrollArea>`,
  importSnippet: `import ScrollArea from "@/components/ui/scroll-area/scroll-area.marko";`,
  usageSnippet: `<ScrollArea class="h-[200px] w-[350px] rounded-md border p-4">
  Your scrollable content here.
</ScrollArea>`,
  // Single-file component: the real anatomy (root, viewport, content,
  // per-orientation scrollbar + thumb, corner) is generated by the
  // @zag-js/scroll-area machine, so api-reference.json only sees one part
  // and `isCompound` is false — the auto-generated <composition-tree>
  // never renders. Documented here instead, matching upstream's
  // Composition section (upstream: `ScrollArea └── ScrollBar`, a
  // Radix/Base-UI split we don't have — our single tag owns both
  // scrollbars via the `horizontal`/`vertical` boolean props below).
  composition: `\`ScrollArea\` is a single tag; there is no separate \`ScrollBar\` part to compose. Internally it renders:

\`\`\`text
ScrollArea (root)
└── viewport
    └── content (your children)
└── scrollbar (vertical, default on)
    └── thumb
└── scrollbar (horizontal, opt-in via \`horizontal\`)
    └── thumb
└── corner
\`\`\`

Pass \`horizontal\` to render the horizontal scrollbar and thumb alongside the vertical one, and \`vertical={false}\` to suppress the vertical scrollbar for horizontal-only rails.`,
  examples: [
    {
      name: "scroll-area-demo",
      title: "Vertical",
      description: "A vertical scroll area with a synthetic, auto-hiding draggable thumb.",
    },
    {
      name: "scroll-area-horizontal-demo",
      title: "Horizontal",
      description: "Pass `horizontal` to render a horizontal scrollbar and thumb alongside the vertical one.",
    },
    {
      name: "scroll-area-rtl",
      title: "RTL",
      description: "ScrollArea restyles correctly under `dir=\"rtl\"` with no component changes.",
    },
  ],
  // Deviates from upstream, which links out to Base UI's accessibility
  // docs with no keyboard table. Documented here from our actual markup
  // (packages/shadcn/ui/scroll-area/scroll-area.marko): the viewport
  // carries tabindex="0" specifically so a scrollable region with no
  // otherwise-focusable content is still keyboard-reachable (axe rule
  // scrollable-region-focusable) — the scrollbars themselves are Zag's
  // synthetic drag-only thumbs and are not part of the tab sequence.
  accessibilityNotes: [
    "The scrollable viewport is focusable (`tabindex=\"0\"`) even when its content has no focusable elements, so keyboard users can tab to it and scroll with arrow keys.",
    "The scrollbar thumbs are draggable with a pointer but are not separately focusable — they are visual/pointer affordances layered over native keyboard scrolling on the viewport.",
  ],
};
