/**
 * Generates src/lib/cli-manifest.ts from the CLI's own `manifest` command,
 * so /docs/cli renders a reference that cannot drift from the real surface.
 *
 * Mirrors the committed-output pattern of build-demos-manifest.ts: the
 * generated module is checked in and rebuilt by this script — no
 * request-time filesystem or subprocess work.
 *
 * Usage: bun apps/docs/scripts/build-cli-manifest.ts
 * (builds the CLI first if dist/ is missing)
 */
import { execFileSync } from "node:child_process";
import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const CLI_DIR = join(ROOT, "packages/cli");
const CLI_BIN = join(CLI_DIR, "dist/index.js");
const OUT_FILE = join(ROOT, "apps/docs/src/lib/cli-manifest.ts");

if (!existsSync(CLI_BIN)) {
  console.log("cli-manifest: building @marko-ui/cli first…");
  execFileSync("bun", ["run", "build"], { cwd: CLI_DIR, stdio: "inherit" });
}

const raw = execFileSync("node", [CLI_BIN, "manifest"], { encoding: "utf8" });
const manifest = JSON.parse(raw);

const banner = `// GENERATED by apps/docs/scripts/build-cli-manifest.ts — do not edit.
// Rebuild with: bun apps/docs/scripts/build-cli-manifest.ts
`;

const types = `export type CliOption = {
  flags: string;
  description: string;
  defaultValue?: unknown;
};

export type CliArgument = {
  name: string;
  required: boolean;
  variadic: boolean;
  description?: string;
};

export type CliCommand = {
  name: string;
  aliases: string[];
  description: string;
  arguments: CliArgument[];
  options: CliOption[];
  subcommands?: CliCommand[];
};

export type CliManifest = {
  cliVersion: string;
  commands: CliCommand[];
  exitCodes: Record<string, string>;
  agentWorkflow: string[];
};
`;

const data = `export const CLI_MANIFEST: CliManifest = ${JSON.stringify(
  {
    cliVersion: manifest.data.cliVersion,
    commands: manifest.data.commands,
    exitCodes: manifest.data.exitCodes,
    agentWorkflow: manifest.data.agentWorkflow,
  },
  null,
  2,
)};
`;

await writeFile(OUT_FILE, `${banner}\n${types}\n${data}`);
console.log(
  `cli-manifest: ${manifest.data.commands.length} commands → src/lib/cli-manifest.ts (cli ${manifest.data.cliVersion})`,
);
