/**
 * Generates a style-matrix verification tree: for every (style, component,
 * demo) combination, a copied+import-rewritten demo tag under
 * src/tags/verify/<style>/<component>/<demo>.marko, and one static route per
 * (style, component) pair at src/routes/verify/<style>/<component>/+page.marko
 * that statically imports and renders all of that pair's demo tags.
 *
 * Why copy each demo into its own tag file rather than combining them: this
 * mirrors build-demos-manifest.ts's approach and its documented reasons —
 * (1) a `.marko` file outside src/tags/ that imports many sibling `.marko`
 * files AND is itself imported as a custom tag fails to compile ("Unable to
 * find entry point for custom tag"), so generated tags live under
 * src/tags/verify/; (2) copying per-demo avoids import-identifier collisions
 * that would occur if multiple demos (each importing "Button" from a
 * different style) were concatenated into one file.
 *
 * Why one static route per (style, component) instead of a dynamic
 * `[style]/[component]` route: Marko 6.3.34 crashes client hydration when a
 * dynamic tag reference is resolved from a runtime lookup (see
 * notes/bug-marko-dynamic-tag-hydration-crash.md and
 * build-demos-manifest.ts's header) — anything rendered per-route here must
 * be statically imported, so each pair gets its own generated route file
 * with literal imports.
 *
 * Run: bun apps/docs/scripts/build-verify-matrix.ts
 */
import { existsSync } from "node:fs";
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";

// Syntax-only check (no module resolution) for every .ts file under a
// registry component directory. Vite/marko-run's SSR module graph appears to
// eagerly build (and cache-poison on failure) across ALL generated routes at
// once, not lazily per request — one unparseable .ts anywhere in the tree
// took down the entire dev server, including unrelated pre-existing routes
// (verified empirically: a stray `*/` inside a JSDoc comment in
// packages/registry/styles/maia/ui/drawer/variants.ts, a genuine registry
// authoring bug that terminates the block comment early and leaves prose as
// bare invalid TS). Since registry files are off-limits to fix, any
// component whose .ts files don't parse is excluded from generation up
// front so the rest of the matrix can build and boot the dev server.
const tsTranspiler = new Bun.Transpiler({ loader: "ts" });
async function componentTsFilesParse(componentDir: string): Promise<{ ok: boolean; error?: string }> {
  const entries = await readdir(componentDir, { withFileTypes: true, recursive: true }).catch(() => []);
  for (const entry of entries) {
    if (!entry.isFile() || !entry.name.endsWith(".ts")) continue;
    const path = join(entry.parentPath ?? componentDir, entry.name);
    const source = await readFile(path, "utf8");
    try {
      tsTranspiler.transformSync(source);
    } catch (error) {
      return { ok: false, error: `${path}: ${(error as Error).message}` };
    }
  }
  return { ok: true };
}

const DOCS_APP = new URL("../", import.meta.url).pathname;
const DEMOS_DIR = join(DOCS_APP, "src/demos");
const TAGS_OUT_DIR = join(DOCS_APP, "src/tags/verify");
const ROUTES_OUT_DIR = join(DOCS_APP, "src/routes/verify");
const REGISTRY_DIR = new URL("../../../packages/registry/", import.meta.url).pathname;

/** Files in src/demos/ that are infrastructure, not a documented component. */
const NON_COMPONENT_ENTRIES = new Set(["docs-types.ts", "demos-manifest.ts"]);

/** Style ids, in the order they should be generated/reported. "default" needs no import rewrite. */
const STYLES = ["default", "luma", "lyra", "maia", "mira", "nova", "rhea", "sera", "vega"] as const;
type Style = (typeof STYLES)[number];

const GENERATED_HEADER = "// GENERATED by build-verify-matrix.ts — do not edit\n";

/** `switch-demo` / `switch` → `switch/switch-demo`, matches build-demos-manifest.ts's id convention. */
function toDemoId(componentName: string, exampleName: string): string {
  return `${componentName}/${exampleName}`;
}

/** `switch-demo` → `Demo_switch_switch_demo`, safe as a JS identifier. */
function toIdentifier(componentName: string, exampleName: string): string {
  return `Demo_${`${componentName}_${exampleName}`.replace(/[^A-Za-z0-9]+/g, "_")}`;
}

async function componentDirectories(): Promise<string[]> {
  const entries = await readdir(DEMOS_DIR, { withFileTypes: true });
  return entries
    .filter((entry) => entry.isDirectory() && !NON_COMPONENT_ENTRIES.has(entry.name))
    .map((entry) => entry.name)
    .sort();
}

/** Style root for a component's registry directory, or null if the style doesn't ship that component. */
function styleComponentDir(style: Style, componentName: string): string {
  return style === "default"
    ? join(REGISTRY_DIR, "default/ui", componentName)
    : join(REGISTRY_DIR, "styles", style, "ui", componentName);
}

/** Rewrites `@marko-ui/registry/ui/` import specifiers to the target style's package path. Default style is a no-op. */
function rewriteImports(source: string, style: Style): string {
  if (style === "default") return source;
  return source.replace(
    /from\s+(["'])@marko-ui\/registry\/ui\//g,
    (_match, quote: string) => `from ${quote}@marko-ui/registry/styles/${style}/ui/`,
  );
}

/**
 * Every `@marko-ui/registry/ui/<component>/<file>.marko` import path referenced
 * by a demo's source, as `<component>/<file>.marko` pairs. Checking at the
 * exact-file level (not just "does the component directory exist") matters:
 * a style can ship a component directory that's missing one of its part
 * files — e.g. lyra's native-select/ has native-select.marko but not
 * native-select-option.marko — and importing that specific missing file
 * fails Vite's dependency scan for the WHOLE dev server, not just that route
 * (verified empirically: it took down unrelated pages like "/").
 */
function importedRegistryFiles(source: string): Array<{ component: string; file: string }> {
  const results: Array<{ component: string; file: string }> = [];
  for (const match of source.matchAll(/@marko-ui\/registry\/ui\/([^"'\s]+\.marko)/g)) {
    const fullPath = match[1]!;
    const slashIndex = fullPath.indexOf("/");
    if (slashIndex === -1) continue;
    results.push({ component: fullPath.slice(0, slashIndex), file: fullPath.slice(slashIndex + 1) });
  }
  return results;
}

interface DemoRecord {
  componentName: string;
  exampleName: string;
  demoId: string;
}

interface SkipRecord {
  style: string;
  component: string;
  demo?: string;
  reason: string;
}

interface ManifestEntry {
  style: string;
  component: string;
  route: string;
  demos: string[];
}

async function main() {
  const components = await componentDirectories();

  // Reset generated trees so stale pairs/demos from a previous run never linger.
  await rm(TAGS_OUT_DIR, { recursive: true, force: true });
  await rm(ROUTES_OUT_DIR, { recursive: true, force: true });

  // Discover demo files per component up front (shared across all styles).
  const demosByComponent = new Map<string, DemoRecord[]>();
  for (const componentName of components) {
    const componentDir = join(DEMOS_DIR, componentName);
    const files = await readdir(componentDir);
    const exampleNames = files
      .filter((file) => file.endsWith(".marko"))
      .map((file) => file.slice(0, -".marko".length))
      .sort();
    demosByComponent.set(
      componentName,
      exampleNames.map((exampleName) => ({
        componentName,
        exampleName,
        demoId: toDemoId(componentName, exampleName),
      })),
    );
  }

  const skips: SkipRecord[] = [];
  const manifestEntries: ManifestEntry[] = [];
  let pagesGenerated = 0;
  let demosGenerated = 0;

  // key: `${style}/${componentName}` -> parse error message, populated lazily.
  const tsParseCache = new Map<string, string | null>();
  async function tsErrorFor(style: Style, componentName: string): Promise<string | null> {
    const key = `${style}/${componentName}`;
    if (tsParseCache.has(key)) return tsParseCache.get(key)!;
    const dir = styleComponentDir(style, componentName);
    const result = existsSync(dir) ? await componentTsFilesParse(dir) : { ok: true as const };
    const error = result.ok ? null : result.error!;
    tsParseCache.set(key, error);
    return error;
  }

  for (const style of STYLES) {
    for (const componentName of components) {
      const demos = demosByComponent.get(componentName) ?? [];
      const componentDir = styleComponentDir(style, componentName);

      if (!existsSync(componentDir)) {
        skips.push({
          style,
          component: componentName,
          reason: `style "${style}" has no packages/registry component directory for "${componentName}"`,
        });
        continue;
      }

      const ownTsError = await tsErrorFor(style, componentName);
      if (ownTsError) {
        skips.push({
          style,
          component: componentName,
          reason: `registry bug — .ts file fails to parse (excluded so the dev server can boot): ${ownTsError}`,
        });
        continue;
      }

      const tagDir = join(TAGS_OUT_DIR, style, componentName);
      const includedDemos: DemoRecord[] = [];
      const tagImportLines: string[] = [];
      const sectionLines: string[] = [];

      for (const demo of demos) {
        const demoSourcePath = join(DEMOS_DIR, componentName, `${demo.exampleName}.marko`);
        const source = await readFile(demoSourcePath, "utf8");
        const requiredFiles = importedRegistryFiles(source);
        const missing = requiredFiles.filter(
          ({ component, file }) => !existsSync(join(styleComponentDir(style, component), file)),
        );

        if (missing.length !== 0) {
          skips.push({
            style,
            component: componentName,
            demo: demo.exampleName,
            reason: `demo imports registry file(s) not present in style "${style}": ${missing
              .map((m) => `${m.component}/${m.file}`)
              .join(", ")}`,
          });
          continue;
        }

        const crossImportedComponents = [...new Set(requiredFiles.map((f) => f.component))].filter(
          (name) => name !== componentName,
        );
        const crossTsErrors: string[] = [];
        for (const name of crossImportedComponents) {
          const error = await tsErrorFor(style, name);
          if (error) crossTsErrors.push(`${name}: ${error}`);
        }
        if (crossTsErrors.length !== 0) {
          skips.push({
            style,
            component: componentName,
            demo: demo.exampleName,
            reason: `demo cross-imports registry component(s) with a .ts parse error in style "${style}" (registry bug): ${crossTsErrors.join("; ")}`,
          });
          continue;
        }

        const rewritten = rewriteImports(source, style);
        await mkdir(tagDir, { recursive: true });
        await writeFile(join(tagDir, `${demo.exampleName}.marko`), GENERATED_HEADER + rewritten);
        demosGenerated++;

        const identifier = toIdentifier(componentName, demo.exampleName);
        tagImportLines.push(`import ${identifier} from "../../../../tags/verify/${style}/${componentName}/${demo.exampleName}.marko";`);
        sectionLines.push(
          `<section data-demo=${JSON.stringify(demo.exampleName)}>\n  <${identifier}/>\n</section>`,
        );
        includedDemos.push(demo);
      }

      if (includedDemos.length === 0) {
        // Every demo was skipped (or the component has none) — no route to generate.
        if (demos.length !== 0) {
          skips.push({
            style,
            component: componentName,
            reason: "all demos skipped for this style (see individual demo skip reasons above)",
          });
        }
        continue;
      }

      const routeDir = join(ROUTES_OUT_DIR, style, componentName);
      await mkdir(routeDir, { recursive: true });
      const pageContent =
        GENERATED_HEADER +
        `${tagImportLines.join("\n")}\n\n` +
        `<main data-verify-style=${JSON.stringify(style)} data-verify-component=${JSON.stringify(componentName)}>\n` +
        sectionLines.map((s) => indent(s, "  ")).join("\n") +
        `\n</main>\n`;
      await writeFile(join(routeDir, "+page.marko"), pageContent);
      pagesGenerated++;

      manifestEntries.push({
        style,
        component: componentName,
        route: `/verify/${style}/${componentName}`,
        demos: includedDemos.map((d) => d.exampleName),
      });
    }
  }

  await mkdir(ROUTES_OUT_DIR, { recursive: true });
  const manifest = {
    generatedAt: new Date().toISOString(),
    styles: STYLES,
    totals: {
      pagesGenerated,
      demosGenerated,
      skips: skips.length,
    },
    entries: manifestEntries,
    skips,
  };
  await writeFile(join(ROUTES_OUT_DIR, "manifest.json"), JSON.stringify(manifest, null, 2) + "\n");

  console.log(
    `build-verify-matrix: generated ${pagesGenerated} routes / ${demosGenerated} demo tags, ${skips.length} skips.`,
  );
}

function indent(text: string, prefix: string): string {
  return text
    .split("\n")
    .map((line) => (line.length === 0 ? line : prefix + line))
    .join("\n");
}

main();
