/**
 * Writes every component's Usage snippet, exactly as `marko-ui docs` renders
 * it for an `import`-distribution project, to
 * apps/docs/src/usage-snippets/<name>.marko.
 *
 * Why: a Usage snippet is the code an agent pastes first, and as a string in
 * docs.ts it is type-checked by nothing — `checked:=` into a `<let>` typed
 * `boolean`, or an `items=` array whose `type` widened to `string`, shipped
 * green and fails the first type gate of any project that pastes it. Emitted
 * as `.marko` files under `src/`, the snippets fall inside apps/docs's
 * `src/**\/*.marko` include, so the docs mtc gate (scripts/check.sh) checks
 * them like any other template — no second type-check harness. The `import`
 * style is the one that resolves in this workspace (`@marko-ui/shadcn/ui/…`),
 * and it is the style that imports every tag, so nothing relies on a taglib.
 *
 * The files are generated: run by `bun run build:demos`, committed, and kept
 * fresh by CI's registry-drift job like the other build:demos outputs.
 */
import { mkdir, readdir, rm, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { resolveUsage } from "../../../packages/marko-ui/src/docs/render.ts";
import { buildComponentDocs } from "../../../packages/marko-ui/src/docs/build.ts";
import { DOCUMENTED_COMPONENTS, getComponentPageData } from "../src/lib/component-page-data.ts";
import { componentDocsInputFromPage } from "../src/lib/component-markdown.ts";

const OUT_DIR = new URL("../src/usage-snippets/", import.meta.url).pathname;

const HEADER =
  "// GENERATED by apps/docs/scripts/build-usage-snippets.ts from the component's\n" +
  "// docs.ts Usage snippet — do not edit; edit the docs.ts and run `bun run build:demos`.\n";

await rm(OUT_DIR, { recursive: true, force: true });
await mkdir(OUT_DIR, { recursive: true });
let written = 0;
for (const name of DOCUMENTED_COMPONENTS) {
  const page = getComponentPageData(name);
  if (!page) continue;
  const { block } = resolveUsage(buildComponentDocs(componentDocsInputFromPage(page)), {
    kind: "import",
  });
  await writeFile(join(OUT_DIR, `${name}.marko`), `${HEADER}${block}\n`);
  written += 1;
}
console.log(`usage snippets: wrote ${written} file(s) to ${OUT_DIR} (${(await readdir(OUT_DIR)).length} present)`);
