/**
 * Generates apps/docs/src/lib/blocks-manifest.ts — the static data source for
 * the block viewer (BlockViewerCode + BlockViewerFileTree, faithfully ported
 * from shadcn/ui's block-viewer.tsx).
 *
 * Reads each block's already-built registry JSON from apps/docs/public/r/
 * (emitted by `bun run build:registry`) and inlines its `files[]` (path,
 * target, content) plus a precomputed file tree as literal TypeScript — the
 * same "generate, don't read at request time" pattern build-demos-manifest.ts
 * uses, for the same reason: the source tree does not ship in the production
 * container's dist/index.mjs, so a module-scope or request-time filesystem
 * read of packages/shadcn/** or apps/docs/public/r/** would ENOENT on boot
 * (see notes/bug commit 55f21c4, "inline typeset.css at build time").
 *
 * Run (after `bun run build:registry`): bun apps/docs/scripts/build-blocks-manifest.ts
 */
import { readFile, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { BLOCKS } from "../src/lib/blocks-list.ts";

const DOCS_APP = new URL("../", import.meta.url).pathname;
const REGISTRY_OUT_DIR = join(DOCS_APP, "public/r");
const OUT_FILE = join(DOCS_APP, "src/lib/blocks-manifest.ts");

interface RegistryFile {
  path: string;
  target: string;
  content: string;
}

interface RegistryItem {
  name: string;
  title?: string;
  description?: string;
  files?: RegistryFile[];
}

// Mirrors shadcn's lib/registry.ts createFileTreeForRegistryItemFiles: turns
// a flat list of `target` paths into a nested folder tree, keyed off the
// path segments after the block's own route directory. Our registry targets
// blocks at `~/src/routes/<block-name>/<file>`, one level deep in practice,
// but this walks arbitrary depth like the source does.
interface FileTreeNode {
  name: string;
  path?: string;
  children?: FileTreeNode[];
}

function targetSegments(target: string): string[] {
  // "~/src/routes/login-01/login-form.marko" -> ["login-01", "login-form.marko"]
  const withoutPrefix = target.replace(/^~\/src\/routes\//, "");
  return withoutPrefix.split("/").filter(Boolean);
}

function buildFileTree(files: RegistryFile[]): FileTreeNode[] {
  const root: FileTreeNode[] = [];

  for (const file of files) {
    const segments = targetSegments(file.target);
    let cursor = root;

    for (let index = 0; index < segments.length; index++) {
      const segment = segments[index];
      const isLeaf = index === segments.length - 1;

      if (isLeaf) {
        cursor.push({ name: segment, path: file.target });
        continue;
      }

      let dir = cursor.find((node) => node.name === segment && node.children);
      if (!dir) {
        dir = { name: segment, children: [] };
        cursor.push(dir);
      }
      cursor = dir.children!;
    }
  }

  return root;
}

async function readRegistryItem(name: string): Promise<RegistryItem | null> {
  try {
    const raw = await readFile(join(REGISTRY_OUT_DIR, `${name}.json`), "utf8");
    return JSON.parse(raw) as RegistryItem;
  } catch {
    return null;
  }
}

async function main() {
  const entries: string[] = [];

  for (const block of BLOCKS) {
    const item = await readRegistryItem(block.name);
    if (!item?.files?.length) {
      throw new Error(
        `blocks-manifest: no registry item for block "${block.name}" — run "bun run build:registry" first.`,
      );
    }

    const tree = buildFileTree(item.files);
    // First file target as the default active file, matching BlockViewerProvider's
    // `highlightedFiles?.[0].target ?? null`.
    const defaultFile = item.files[0]?.target ?? null;

    entries.push(
      `  ${JSON.stringify(block.name)}: {\n` +
        `    files: ${JSON.stringify(item.files, null, 6).replace(/\n/g, "\n    ")},\n` +
        `    tree: ${JSON.stringify(tree, null, 6).replace(/\n/g, "\n    ")},\n` +
        `    defaultFile: ${JSON.stringify(defaultFile)},\n` +
        `  },`,
    );
  }

  const output = `// GENERATED by apps/docs/scripts/build-blocks-manifest.ts — do not edit.
// Regenerate after changing anything under packages/shadcn/blocks/
// (run "bun run build:registry" first, then this script):
//   bun apps/docs/scripts/build-blocks-manifest.ts

export interface BlockManifestFile {
  /** Source path relative to packages/shadcn/, e.g. blocks/login-01/page.marko */
  path: string;
  type: string;
  /** Path the shadcn CLI writes this file to in a consumer app. */
  target: string;
  /** Raw file text, inlined at generation time for the code panel. */
  content: string;
}

export interface BlockManifestTreeNode {
  name: string;
  /** Present on leaf nodes (files); matches a BlockManifestFile's target. */
  path?: string;
  children?: BlockManifestTreeNode[];
}

export interface BlockManifestEntry {
  files: BlockManifestFile[];
  tree: BlockManifestTreeNode[];
  /** Target path of the file shown by default in the code panel. */
  defaultFile: string | null;
}

export const BLOCKS_MANIFEST: Record<string, BlockManifestEntry> = {
${entries.join("\n")}
};
`;

  await writeFile(OUT_FILE, output);
  console.log(`blocks-manifest: ${BLOCKS.length} blocks → ${OUT_FILE}`);
}

main().catch((error) => {
  console.error(error);
  process.exit(1);
});
