/**
 * Generates src/lib/cli-manifest.ts from the CLI's own `manifest` command,
 * so /docs/cli renders a reference that cannot drift from the real surface.
 *
 * Mirrors the committed-output pattern of build-demos-manifest.ts: the
 * generated module is checked in and rebuilt by this script — no
 * request-time filesystem or subprocess work.
 *
 * Usage: bun apps/docs/scripts/build-cli-manifest.ts
 *
 * Reads the CLI SOURCE, not `packages/marko-ui/dist`. This used to shell out to
 * the built `dist/index.js` and only built it when `dist/` was missing, so a
 * stale `dist/` (built before a flag landed) silently regenerated a stale
 * manifest, and nothing in CI noticed. `buildManifest(buildProgram())` is the
 * exact function behind `marko-ui manifest`, importable under bun without a
 * build step, so the output is a pure function of the checked-out source: no
 * build to forget, no stale artifact to read, and deterministic (the registry-
 * drift job regenerates and diffs it).
 */
import { writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { buildManifest } from "../../../packages/marko-ui/src/commands/manifest.ts";
import { buildProgram } from "../../../packages/marko-ui/src/index.ts";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "../../..");
const OUT_FILE = join(ROOT, "apps/docs/src/lib/cli-manifest.ts");

const manifest = buildManifest(buildProgram());

const banner = `// GENERATED by apps/docs/scripts/build-cli-manifest.ts — do not edit.
// Rebuild with: bun apps/docs/scripts/build-cli-manifest.ts
`;

const types = `export type CliOption = {
  flags: string;
  description: string;
  defaultValue?: unknown;
};

export type CliArgument = {
  name: string;
  required: boolean;
  variadic: boolean;
  description?: string;
};

export type CliCommand = {
  name: string;
  aliases: string[];
  description: string;
  arguments: CliArgument[];
  options: CliOption[];
  subcommands?: CliCommand[];
};

export type CliManifest = {
  cliVersion: string;
  commands: CliCommand[];
  exitCodes: Record<string, string>;
  /** Stable machine-readable warning codes, next to the error codes in the
   *  CLI's own manifest. Carried here so the docs page can list one
   *  vocabulary for both outcomes. */
  warningCodes?: string[];
  agentWorkflow: string[];
};
`;

const data = `export const CLI_MANIFEST: CliManifest = ${JSON.stringify(
  {
    cliVersion: manifest.data.cliVersion,
    commands: manifest.data.commands,
    exitCodes: manifest.data.exitCodes,
    warningCodes: manifest.data.warningCodes,
    agentWorkflow: manifest.data.agentWorkflow,
  },
  null,
  2,
)};
`;

await writeFile(OUT_FILE, `${banner}\n${types}\n${data}`);
console.log(
  `cli-manifest: ${manifest.data.commands.length} commands → src/lib/cli-manifest.ts (cli ${manifest.data.cliVersion})`,
);
