// Generates one static route per documented component under
// src/bare-routes/bare/<component>/+page.marko, each importing ONLY that
// component's default demo (the first entry of its docs.ts `examples`).
//
// Why generated per-component routes instead of a single `bare/$component`
// route with a runtime lookup: the bare pages are Lighthouse fixtures, so
// their client bundle must contain just the one demo. A dynamic route would
// need either a dynamic tag (<${...}/>) — which crashes Marko 6.3.46 client
// hydration in production builds (notes/bug-marko-dynamic-tag-hydration-crash.md)
// — or the generated demo-renderer.marko, which statically imports all ~700
// demos and would put every demo's JS in every bare page. One generated file
// per component keeps each page's bundle to its own demo; the static adapter
// seeds parameterless routes automatically, so no url list is needed.
//
// Regenerate (runs automatically before the bare build): bun scripts/build-bare-routes.ts
import * as fs from "node:fs";
import * as path from "node:path";

import { COMPONENTS } from "../src/lib/components-list.ts";

const root = path.join(import.meta.dir, "..");
const outDir = path.join(root, "src/bare-routes/bare");

// The demo the docs hero renders is examples[0] (see lib/component-page-data.ts);
// the bare page must render the same one or it measures a different thing.
async function defaultDemo(name: string): Promise<string> {
  const mod = await import(`../src/demos/${name}/docs.ts`);
  const example = mod.docs.examples?.[0];
  if (!example) throw new Error(`${name}: docs.ts has no examples`);
  const demoFile = path.join(root, `src/demos/${name}/${example.name}.marko`);
  if (!fs.existsSync(demoFile)) {
    throw new Error(`${name}: first example ${example.name} has no ${demoFile}`);
  }
  return example.name;
}

// Start clean so renamed/removed components do not leave stale routes behind.
fs.rmSync(outDir, { recursive: true, force: true });

let written = 0;
for (const name of COMPONENTS) {
  const demo = await defaultDemo(name);
  const dir = path.join(outDir, name);
  fs.mkdirSync(dir, { recursive: true });
  // ../../../demos/<name>/<demo>.marko resolves from src/bare-routes/bare/<name>/.
  fs.writeFileSync(
    path.join(dir, "+page.marko"),
    `// GENERATED by apps/docs/scripts/build-bare-routes.ts — do not edit.
// Renders ${name}'s default demo (docs.ts examples[0]) as a chrome-free
// Lighthouse fixture; see scripts/build-bare-routes.ts for why.
import Demo from "../../../demos/${name}/${demo}.marko";

<Demo/>
`,
  );
  written++;
}

// Keep the generated tree out of git; this script is the source of truth.
const gitignore = path.join(root, "src/bare-routes/bare/.gitignore");
fs.writeFileSync(gitignore, "# Generated by scripts/build-bare-routes.ts\n*\n");

console.log(`bare routes: wrote ${written} pages to src/bare-routes/bare/`);
