#!/usr/bin/env bash
# Regenerates apps/docs/mtc-baseline.txt from a fresh marko-type-check run.
# Run this after fixing or otherwise legitimately changing any of the known
# upstream errors baked into the baseline (see the header this script writes
# into that file for what they are and why they're accepted as known).
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

rm -f tsconfig.tsbuildinfo
raw="$(NODE_OPTIONS="--max-old-space-size=8192" marko-type-check -p ./tsconfig.json -d condensed || true)"
fingerprint="$(printf '%s' "$raw" | bun scripts/normalize-mtc.ts)"

{
  cat <<'HEADER'
# apps/docs marko-type-check baseline.
#
# GENERATED by scripts/generate-mtc-baseline.sh — do not hand-edit.
# Regenerate with: bun run mtc:baseline (from apps/docs)
#
# This is a KNOWN-error baseline, not a target of zero. apps/docs has one
# genuinely single-file typecheck project (SITE and DEMOS could not be split
# into separate mtc projects — see AGENTS.md's "docs mtc: known limitation"
# section for why marko-type-check ignores tsconfig exclude for .marko
# files). The bulk of these errors are the documented upstream
# @marko/language-tools attr-tag codegen mismatch: a parameterless,
# text-only attr-tag's synthesized type can't be satisfied by any runtime
# value, including the correctly-shaped one (see root AGENTS.md's
# "A parameterless, text-only attr-tag" paragraph). They are not fixable
# from this repo.
#
# check.sh diffs a fresh run's fingerprint against this file:
#   - a NEW line (an error not in this baseline) fails the check — that's
#     the real regression gate.
#   - a line that DISAPPEARS (a baseline error no longer reproducing) also
#     fails the check, with a message to regenerate — so a real fix doesn't
#     silently coast on a stale baseline forever.
#
# Format: one line per distinct error, `path|TScode|first-80-chars-of-message`,
# deduped with a trailing `xN` when the same fingerprint repeats (e.g. the
# same attr-tag bug hit N times in one file). Line numbers are deliberately
# NOT part of the key — an unrelated edit that shifts existing errors up or
# down a few lines must not look like new+removed errors here.
HEADER
  echo "#"
  echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  printf '%s\n' "$fingerprint"
} > mtc-baseline.txt

echo "Wrote mtc-baseline.txt ($(printf '%s' "$fingerprint" | grep -c . || true) entries)" >&2
