#!/usr/bin/env bash
# Regenerates apps/docs/mtc-baseline.txt from a fresh marko-type-check run.
# Run this after fixing or otherwise legitimately changing any of the known
# upstream errors baked into the baseline (see the header this script writes
# into that file for what they are and why they're accepted as known).
set -euo pipefail

cd "$(dirname "${BASH_SOURCE[0]}")/.."

bash scripts/ensure-routes-dts.sh
rm -f tsconfig.tsbuildinfo
set +e
raw="$(NODE_OPTIONS="--max-old-space-size=8192" marko-type-check -p ./tsconfig.json -d condensed)"
mtc_exit=$?
set -e

# marko-type-check only ever exits 0 (no errors) or 1 (has errors) when it
# ran to completion; anything else (137/139 killed, 124 timed out, ...)
# means it crashed before finishing. Refuse to write a baseline from that —
# its (likely empty) stdout would otherwise be recorded as "zero known
# errors", silently erasing the whole gate on the next check.sh run.
if [ "$mtc_exit" -ne 0 ] && [ "$mtc_exit" -ne 1 ]; then
  echo "marko-type-check did not complete (crash/OOM?) — refusing to write mtc-baseline.txt (exit $mtc_exit)." >&2
  exit 1
fi

fingerprint="$(printf '%s' "$raw" | bun scripts/normalize-mtc.ts)"

# normalize-mtc.ts classifies every blank-line-delimited record it sees —
# as a fingerprinted error, or as a recognized-and-skipped non-error — and
# never silently drops one. --count reports "<rawRecords> <accountedRecords>";
# a mismatch means a future change to that file's classification logic
# introduced a silent drop. Refuse to write a baseline built from that.
read -r raw_record_count accounted_record_count <<< "$(printf '%s' "$raw" | bun scripts/normalize-mtc.ts --count)"
if [ "$raw_record_count" != "$accounted_record_count" ]; then
  echo "normalize-mtc.ts saw $raw_record_count raw diagnostic record(s) but only accounted for $accounted_record_count — normalizer gap, not a clean run. Refusing to write mtc-baseline.txt." >&2
  exit 1
fi

# Same crash shape as check.sh: an existing non-trivial baseline going to
# zero entries in one run is far more likely a truncated run than every
# error having been fixed at once. Refuse rather than silently wiping it,
# unless the caller passes --force to confirm this really is "every known
# error got fixed," not a crash.
if [ -z "$fingerprint" ] && [ -f mtc-baseline.txt ] && [ -n "$(grep -v '^#' mtc-baseline.txt | sed '/^$/d')" ] && [ "${1:-}" != "--force" ]; then
  echo "marko-type-check produced no errors but the existing baseline is non-empty — this looks like a crashed/truncated run, not a clean fix. Refusing to overwrite mtc-baseline.txt. If every known error genuinely got fixed, rerun with --force." >&2
  exit 1
fi

{
  cat <<'HEADER'
# apps/docs marko-type-check baseline.
#
# GENERATED by scripts/generate-mtc-baseline.sh — do not hand-edit.
# Regenerate with: bun run mtc:baseline (from apps/docs)
#
# This is a KNOWN-error baseline, not inherently a target of zero -- but as
# of 2026-09-15 it genuinely holds zero entries: every previously-known
# docs-site type error got fixed (see AGENTS.md's baseline-figures
# paragraph and scratch/team-lead/report-docs-type-cleanup.md for the
# history). apps/docs has one genuinely single-file typecheck project
# (SITE and DEMOS could not be split into separate mtc projects — see
# AGENTS.md's "docs mtc: known limitation" section for why marko-type-check
# ignores tsconfig exclude for .marko files), so if new entries appear here
# in the future, don't assume they're upstream/unfixable just because a
# past baseline's header once said so — check each on its own merits.
#
# check.sh diffs a fresh run's fingerprint against this file:
#   - a NEW line (an error not in this baseline) fails the check — that's
#     the real regression gate.
#   - a line that DISAPPEARS (a baseline error no longer reproducing) also
#     fails the check, with a message to regenerate — so a real fix doesn't
#     silently coast on a stale baseline forever.
#
# Format: one line per distinct error, `path|TScode|first-80-chars-of-message`,
# deduped with a trailing `xN` when the same fingerprint repeats (e.g. the
# same attr-tag bug hit N times in one file). Line numbers are deliberately
# NOT part of the key — an unrelated edit that shifts existing errors up or
# down a few lines must not look like new+removed errors here.
HEADER
  echo "#"
  echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo
  printf '%s\n' "$fingerprint"
} > mtc-baseline.txt

echo "Wrote mtc-baseline.txt ($(printf '%s' "$fingerprint" | grep -c . || true) entries)" >&2
