export interface OpenStateConfig {
  trigger: string;
  content: string;
  open?: "click" | "hover" | "focus" | "right-click";
  key?: string; // used to specify key to press if necessary
}

export const OPEN_STATES: Record<string, OpenStateConfig> = {
  "accordion": { trigger: '[data-slot="accordion-trigger"]', content: '[data-slot="accordion-content"]', open: "click" },
  "alert-dialog": { trigger: '[data-slot="alert-dialog-trigger"]', content: '[data-slot="alert-dialog-content"]', open: "click" },
  "cascade-select": { trigger: '[data-slot="cascade-select-trigger"]', content: '[data-slot="cascade-select-content"]', open: "click" },
  "collapsible": { trigger: '[data-slot="collapsible-trigger"]', content: '[data-slot="collapsible-content"]', open: "click" },
  "color-picker": { trigger: '[data-slot="color-picker-trigger"]', content: '[data-slot="color-picker-content"]', open: "click" },
  "combobox": { trigger: '[data-slot="combobox-trigger"]', content: '[data-slot="combobox-content"]', open: "click" },
  "context-menu": { trigger: '[data-slot="context-menu-trigger"]', content: '[data-slot="context-menu-content"]', open: "right-click" },
  "date-picker": { trigger: '[data-slot="date-picker-trigger"]', content: '[data-slot="date-picker-content"]', open: "click" },
  "dialog": { trigger: '[data-slot="dialog-trigger"]', content: '[data-slot="dialog-content"]', open: "click" },
  "drawer": { trigger: '[data-slot="drawer-trigger"]', content: '[data-slot="drawer-content"]', open: "click" },
  "dropdown-menu": { trigger: '[data-slot="dropdown-menu-trigger"]', content: '[data-slot="dropdown-menu-content"]', open: "click" },
  "floating-panel": { trigger: '[data-slot="floating-panel-trigger"]', content: '[data-slot="floating-panel"]', open: "click" },
  "hover-card": { trigger: '[data-slot="hover-card-trigger"]', content: '[data-slot="hover-card-content"]', open: "hover" },
  "menubar": { trigger: '[data-slot="menubar-trigger"]', content: '[data-slot="menubar-content"]', open: "click" },
  "navigation-menu": { trigger: '[data-slot="navigation-menu-trigger"]', content: '[data-slot="navigation-menu-content"]', open: "click" },
  "popover": { trigger: '[data-slot="popover-trigger"]', content: '[data-slot="popover-content"]', open: "click" },
  "select": { trigger: '[data-slot="select-trigger"]', content: '[data-slot="select-content"]', open: "click" },
  "sheet": { trigger: '[data-slot="sheet-trigger"]', content: '[data-slot="sheet-content"]', open: "click" },
  "tooltip": { trigger: '[data-slot="tooltip-trigger"]', content: '[data-slot="tooltip-content"]', open: "hover" },
  "tour": { trigger: '[data-slot="tour-trigger"]', content: '[data-slot="tour-content"]', open: "click" },
  "tree-view": { trigger: '[data-slot="tree-view-branch-control"]', content: '[data-slot="tree-view-branch-content"]', open: "click" },
};

export const NO_OPEN_STATE: Record<string, string> = {
  "alert": "Static component",
  "angle-slider": "No overlay",
  "aspect-ratio": "Layout component",
  "attachment": "No overlay",
  "avatar": "Static component",
  "badge": "Static component",
  "breadcrumb": "Static component",
  "bubble": "Static component",
  "button": "Static component",
  "button-group": "Static component",
  "calendar": "No overlay",
  "card": "Static component",
  "carousel": "No overlay",
  "chart": "Hover shows tooltip, but uses Recharts internal tooltip for now",
  "checkbox": "No overlay",
  "clipboard": "No overlay",
  "command": "Always open inline component or wrapped in dialog",
  "data-table": "No overlay",
  "date-input": "No overlay",
  "direction": "Provider component",
  "editable": "Swaps inline, no overlay",
  "empty": "Static component",
  "field": "Layout/form wrapper",
  "file-upload": "No overlay",
  "icon": "Static component",
  "image-cropper": "No overlay",
  "input": "No overlay",
  "input-group": "No overlay",
  "input-otp": "No overlay",
  "item": "Internal abstraction",
  "kbd": "Static component",
  "label": "Static component",
  "listbox": "Always open inline list, no trigger/overlay",
  "marker": "Static component",
  "marquee": "No overlay",
  "message": "Static component",
  "message-scroller": "No overlay",
  "native-select": "Native element overlay only",
  "number-input": "No overlay",
  "pagination": "No overlay",
  "password-input": "No overlay",
  "progress": "No overlay",
  "qr-code": "No overlay",
  "radio-group": "No overlay",
  "rating-group": "No overlay",
  "resizable": "No overlay",
  "scroll-area": "No overlay",
  "separator": "Static component",
  "sidebar": "Layout component, scanned as part of page",
  "signature-pad": "No overlay",
  "skeleton": "Static component",
  "slider": "No overlay",
  "sonner": "Programmatically triggered, no component-level trigger",
  "spinner": "Static component",
  "steps": "No overlay",
  "switch": "No overlay",
  "table": "Static component",
  "tabs": "Always has an active tab panel visible",
  "tags-input": "No suggestion overlay implemented",
  "textarea": "No overlay",
  "timer": "No overlay",
  "toast": "Programmatically triggered, no component-level trigger",
  "toc": "No overlay",
  "toggle": "No overlay",
  "toggle-group": "No overlay",
};
