/**
 * axe-core WCAG scan across every component's verify page
 * (/verify/default/<name> — the bare demo matrix pages generated by
 * build-verify-matrix.ts). Those pages render ONLY component demos, so the
 * result measures the components themselves, not the docs-site chrome.
 *
 * Runs against an already-serving docs server (scripts/ci/serve-docs.sh);
 * override the target with DOCS_BASE_URL. Writes a JSON summary (fed to
 * scripts/ci/badge.ts) and exits non-zero when any violation is found, so CI
 * catches a11y regressions.
 *
 * Usage: bun scripts/ci/axe-scan.ts <out-file>
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join } from "node:path";
import type { Page } from "playwright";

const require = createRequire(import.meta.url);
const playwright = require("playwright") as typeof import("playwright");
const axeSource = readFileSync(require.resolve("axe-core/axe.min.js"), "utf8");

const BASE_URL = process.env.DOCS_BASE_URL ?? "http://localhost:3000";
const outFile = process.argv[2];
if (!outFile) {
  console.error("usage: bun scripts/ci/axe-scan.ts <out-file>");
  process.exit(1);
}

const components = readdirSync(join(process.cwd(), "apps/docs/src/routes/verify/default"), {
  withFileTypes: true,
})
  .filter((entry) => entry.isDirectory())
  .map((entry) => entry.name)
  .sort();

const urls = components.map((name) => `/verify/default/${name}`);

interface Violation {
  id: string;
  impact: string | null;
  help: string;
  nodes: number;
  targets: { target: string; html: string }[];
}

/**
 * Page-structure rules that cannot be judged at component scope: the verify
 * pages render inside the docs layout, so landmarks/headings belong to the
 * page, not to the component under test. The scan itself is scoped to the
 * demo <main> (see axe.run include below); these are disabled as well because
 * landmark rules still evaluate page-wide context.
 */
const PAGE_SCOPE_RULES = [
  "landmark-main-is-top-level",
  "landmark-no-duplicate-main",
  "landmark-unique",
  "page-has-heading-one",
  "region",
];

/** Wait for Marko resumption + Zag machine start (same signal the test helpers use). */
async function waitForHydration(page: Page): Promise<void> {
  await page
    .waitForFunction(() => document.querySelector("[data-ssr]") === null, undefined, {
      timeout: 15_000,
    })
    .catch(() => {
      // Static pages (no machines) never carry data-ssr; a timeout here on a
      // hydrated page would have failed the earlier networkidle wait instead.
    });
}

const browser = await playwright.chromium.launch({ headless: true });
const context = await browser.newContext({
  colorScheme: "light",
  viewport: { width: 1280, height: 900 },
});

const perPage: Record<string, Violation[]> = {};
let totalViolations = 0;

for (const path of urls) {
  const page = await context.newPage();
  try {
    await page.goto(`${BASE_URL}${path}`, { waitUntil: "networkidle", timeout: 30_000 });
    await waitForHydration(page);
    await page.addScriptTag({ content: axeSource });
    const results = (await page.evaluate(async (disabledRules: string[]) => {
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const axe = (window as any).axe;
      return axe.run(
        { include: [["main[data-verify-style]"]] },
        {
          resultTypes: ["violations"],
          rules: Object.fromEntries(disabledRules.map((rule) => [rule, { enabled: false }])),
        },
      );
    }, PAGE_SCOPE_RULES)) as {
      violations: {
        id: string;
        impact: string | null;
        help: string;
        nodes: { target: string[]; html: string }[];
      }[];
    };

    const violations: Violation[] = results.violations.map((violation) => ({
      id: violation.id,
      impact: violation.impact,
      help: violation.help,
      nodes: violation.nodes.length,
      targets: violation.nodes.map((node) => ({
        target: node.target.join(" "),
        html: node.html.slice(0, 300),
      })),
    }));
    if (violations.length > 0) {
      perPage[path] = violations;
      totalViolations += violations.reduce((sum, v) => sum + v.nodes, 0);
      console.error(`✗ ${path}: ${violations.map((v) => `${v.id}×${v.nodes}`).join(", ")}`);
    } else {
      console.log(`✓ ${path}`);
    }
  } finally {
    await page.close();
  }
}

await context.close();
await browser.close();

writeFileSync(
  outFile,
  JSON.stringify(
    {
      components: components.length,
      pagesScanned: urls.length,
      violations: totalViolations,
      perPage,
    },
    null,
    2,
  ) + "\n",
);

console.log(
  `\naxe scan: ${urls.length} pages, ${components.length} components, ${totalViolations} violations`,
);
process.exit(totalViolations > 0 ? 1 : 0);
