/**
 * Generate an UNREVIEWED behaviors.ts stub for a component (issue #72).
 *
 * Usage: bun scripts/ci/scaffold-behaviors.ts <component...>
 *
 * Sources, all read statically:
 *   - apps/docs/src/demos/<component>/docs.ts `examples[]`: each example
 *     title becomes an `interaction` stub;
 *   - the zag machine's runtime `props` key list (the machine package the
 *     component's .marko imports): each prop becomes an `api` stub;
 *   - a fixed keyboard / a11y / ssr-hydration stub each (the standard
 *     shape every interactive component has).
 *
 * Every entry is written with `status: "stub"`, which
 * scripts/ci/behavior-coverage.ts treats as NOT countable: stubs stay out
 * of the denominator until a human reviews the entry against the machine /
 * APG pattern (edit it, delete padding, remove the `status` field). A stub
 * file therefore cannot dilute or inflate the coverage number.
 *
 * Never overwrites an existing behaviors.ts.
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import type { ComponentBehavior } from "../../apps/docs/src/demos/behavior-types.ts";

const REPO_ROOT = dirname(dirname(dirname(fileURLToPath(import.meta.url))));

// Machine props that are wiring, not user-facing behavior.
const INFRA_PROPS = new Set(["id", "ids", "getRootNode"]);

export function slugify(text: string): string {
  return text
    .replace(/([a-z0-9])([A-Z])/g, "$1-$2")
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export interface ScaffoldInput {
  component: string;
  /** docs.ts example titles, in page order. */
  exampleTitles: { name: string; title: string }[];
  /** zag machine `props` keys; empty when the component has no machine. */
  machineProps: string[];
  /** e.g. "@zag-js/accordion"; undefined when there is no machine. */
  machinePackage?: string;
}

/** Props worth an api stub: drop wiring keys and `onXChange` handlers whose base prop is present. */
export function relevantProps(props: string[]): string[] {
  const set = new Set(props);
  return props.filter((p) => {
    if (INFRA_PROPS.has(p)) return false;
    const handler = /^on([A-Z]\w*)Change$/.exec(p);
    if (handler) {
      const base = handler[1]![0]!.toLowerCase() + handler[1]!.slice(1);
      if (set.has(base)) return false;
    }
    return true;
  });
}

export function buildStubs(input: ScaffoldInput): ComponentBehavior[] {
  const { component } = input;
  const out: ComponentBehavior[] = [];
  const used = new Set<string>();
  const push = (kind: ComponentBehavior["kind"], slug: string, description: string, source: string) => {
    let id = `${component}/${kind}/${slug}`;
    for (let n = 2; used.has(id); n++) id = `${component}/${kind}/${slug}-${n}`;
    used.add(id);
    out.push({ id, kind, description, source, status: "stub" });
  };

  for (const ex of input.exampleTitles) {
    push(
      "interaction",
      slugify(ex.title),
      `TODO(review): state what the "${ex.title}" example demonstrates, as an observable fact.`,
      `${ex.name}.marko (docs example "${ex.title}")`,
    );
  }
  for (const prop of relevantProps(input.machineProps)) {
    push(
      "api",
      slugify(prop),
      `TODO(review): the effect of the \`${prop}\` prop.`,
      `${input.machinePackage ?? "machine"} Props.${prop}`,
    );
  }
  push("keyboard", "apg-keyboard-contract", "TODO(review): the keyboard contract from the WAI-ARIA APG pattern.", "WAI-ARIA APG");
  push("a11y", "roles-and-labels", "TODO(review): roles / aria-* / accessible name the component exposes.", "WAI-ARIA APG");
  push(
    "ssr-hydration",
    "attributes-stable",
    "Server-rendered ARIA/data attributes are unchanged after client hydration.",
    "packages/shadcn/tests/hydration-coverage.ts",
  );
  return out;
}

export function renderBehaviorsFile(component: string, behaviors: ComponentBehavior[]): string {
  const header = `// UNREVIEWED STUB for ${component} — generated by scripts/ci/scaffold-behaviors.ts.
// Every entry has status: "stub", so behavior-coverage.ts does not count it.
// Review each entry against the machine / APG pattern and the docs: edit the
// description, delete padding, add missing behaviors, then remove \`status\`.
// See notes/behavior-coverage.md.
import type { ComponentBehavior } from "../behavior-types.ts";

`;
  return `${header}export const behaviors: ComponentBehavior[] = ${JSON.stringify(behaviors, null, 2).replace(/^(\s+)"(\w+)":/gm, "$1$2:")};\n`;
}

/** First `@zag-js/*` package the component's .marko files import. */
export function findMachinePackage(uiDir: string): string | undefined {
  if (!existsSync(uiDir)) return undefined;
  for (const file of readdirSync(uiDir).filter((f) => f.endsWith(".marko")).sort()) {
    const m = /from\s+"(@zag-js\/[^"]+)"/.exec(readFileSync(join(uiDir, file), "utf8"));
    if (m) return m[1];
  }
  return undefined;
}

async function loadMachineProps(pkg: string): Promise<string[]> {
  const req = createRequire(join(REPO_ROOT, "packages/shadcn/package.json"));
  const mod = (await import(pathToFileURL(req.resolve(pkg)).href)) as { props?: unknown };
  return Array.isArray(mod.props) ? (mod.props as string[]) : [];
}

export interface ScaffoldResult {
  component: string;
  status: "written" | "exists";
  path: string;
  count: number;
}

export async function scaffoldComponent(
  component: string,
  demosDir = join(REPO_ROOT, "apps/docs/src/demos"),
  uiDir = join(REPO_ROOT, "packages/shadcn/ui", component),
): Promise<ScaffoldResult> {
  const path = join(demosDir, component, "behaviors.ts");
  if (existsSync(path)) return { component, status: "exists", path, count: 0 };

  const docsPath = join(demosDir, component, "docs.ts");
  if (!existsSync(docsPath)) throw new Error(`no docs.ts for "${component}" (${docsPath})`);
  const { docs } = (await import(pathToFileURL(docsPath).href)) as {
    docs: { examples: { name: string; title: string }[] };
  };
  const machinePackage = findMachinePackage(uiDir);
  const machineProps = machinePackage ? await loadMachineProps(machinePackage) : [];
  const behaviors = buildStubs({ component, exampleTitles: docs.examples, machineProps, machinePackage });
  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, renderBehaviorsFile(component, behaviors), { flag: "wx" });
  return { component, status: "written", path, count: behaviors.length };
}

if (import.meta.url === `file://${process.argv[1]}`) {
  const components = process.argv.slice(2);
  if (components.length === 0) {
    console.error("usage: bun scripts/ci/scaffold-behaviors.ts <component...>");
    process.exit(1);
  }
  for (const c of components) {
    const r = await scaffoldComponent(c);
    console.log(
      r.status === "written"
        ? `${c}: wrote ${r.count} stubs → ${r.path}`
        : `${c}: behaviors.ts already exists, left untouched`,
    );
  }
}
