import { MARKO_UI_URL } from "@/src/registry/constants"

import packageJson from "../../package.json"

export const AGENTS_START_MARKER = "<!-- marko-ui:start -->"
export const AGENTS_END_MARKER = "<!-- marko-ui:end -->"

export type InstalledComponent = {
  name: string
  description?: string
}

export type AgentsSectionOptions = {
  /** `components.json`'s distribution. Absent means `copy`. */
  distribution?: "copy" | "import"
}

/**
 * The generated AGENTS.md section. Deliberately small: AGENTS.md is loaded
 * into every agent's context on every task, so it carries only what is
 * specific to THIS project (distribution, installed components) plus the
 * CLI pointers. Deep content lives in the `marko-ui` skill
 * (`skills/marko-ui/SKILL.md` in the repo, installed by the `skills`
 * package — see ./skills.ts), which is loaded on demand.
 *
 * Every command named here must exist: this text is an agent's only
 * instruction for the CLI, and it follows it literally. An earlier version
 * advertised `show <name> --props`, a flag the CLI never had.
 */
export function buildAgentsSection(
  components: InstalledComponent[],
  options: AgentsSectionOptions = {}
) {
  const isImport = options.distribution === "import"

  const intro = isImport
    ? `This project uses [marko-ui](${MARKO_UI_URL}) — shadcn-style components for
Marko 6 — on the \`import\` distribution: every component is already
available from the \`@marko-ui/shadcn\` package
(\`import Button from "@marko-ui/shadcn/ui/button/button.marko"\`), with no
install step. Restyle through the \`mu-*\` hook classes in the project's
stylesheet; never edit files under node_modules.`
    : `This project uses [marko-ui](${MARKO_UI_URL}) — shadcn-style components for
Marko 6, installed as source under the project's \`ui\` directory. You own
these files; edit them directly rather than wrapping them.

Installed components:

${
  components.length
    ? components
        .map(
          (component) =>
            `- \`${component.name}\`${
              component.description ? ` — ${component.description}` : ""
            }`
        )
        .join("\n")
    : "- (none installed yet — run `marko-ui add <name> -y`)"
}`

  const commands = [
    "- `marko-ui docs <name>` — usage, props, and examples as markdown. Read it before using a component.",
    "- `marko-ui search -q <query>` — find a component",
    isImport
      ? null
      : "- `marko-ui add <name> -y` — install one (writes source files and its npm dependencies)",
    "- `marko-ui show <name> --deps` — a component's npm and registry dependencies (`--files` lists its files)",
    "- `marko-ui doctor --json` — verify project health (exit code 3 means a check failed)",
    isImport
      ? "- `marko-ui agents sync` — refresh this section and install the agent skills"
      : "- `marko-ui agents sync` — refresh this section after adding or removing components",
  ]
    .filter(Boolean)
    .join("\n")

  return `${AGENTS_START_MARKER}
<!-- Generated by \`marko-ui agents sync\` (v${packageJson.version}). Edits inside these markers are overwritten. -->

## marko-ui components

${intro}

Use the marko-ui CLI instead of guessing a component's API or writing one
the registry already ships. Run it through the project's package runner
(\`bunx marko-ui\`, \`npx marko-ui\`, \`pnpm dlx marko-ui\`):

${commands}

Before writing or editing component code, load the \`marko-ui\` skill (and
\`marko6\` for Marko 6 syntax). If they are not installed, run
\`marko-ui agents sync\`.
${AGENTS_END_MARKER}`
}
