import { MARKO_UI_URL } from "@/src/registry/constants"

import packageJson from "../../package.json"

export const AGENTS_START_MARKER = "<!-- marko-ui:start -->"
export const AGENTS_END_MARKER = "<!-- marko-ui:end -->"

export type AgentsSectionOptions = {
  /** `components.json`'s distribution. Absent means `copy`. */
  distribution?: "copy" | "import"
}

/**
 * The generated AGENTS.md section. Deliberately small: AGENTS.md is loaded
 * into every agent's context on every task, so it carries only what an agent
 * cannot get elsewhere — the distribution, the installed component names and
 * the CLI pointers. Everything else lives in the `marko-ui` skill
 * (`skills/marko-ui/SKILL.md` in the repo, installed by the `skills`
 * package — see ./skills.ts), which is loaded on demand, so nothing here
 * needs to restate it.
 *
 * Components are names only. They used to carry a one-line description each,
 * which cost ~25 tokens per component on EVERY task and duplicated what
 * `marko-ui docs <name>` already answers on demand.
 *
 * Every command named here must exist: this text is an agent's only
 * instruction for the CLI, and it follows it literally. An earlier version
 * advertised `show <name> --props`, a flag the CLI never had. The check in
 * `src/commands/agents.test.ts` re-derives this text's surface from the live
 * program (and does the same for SKILL.md).
 */
export function buildAgentsSection(
  components: string[],
  options: AgentsSectionOptions = {}
) {
  const isImport = options.distribution === "import"

  const intro = isImport
    ? `marko-ui (<${MARKO_UI_URL}>) — shadcn-style components for Marko 6 — on
the \`import\` distribution: components are already in \`@marko-ui/shadcn\`
(\`import Button from "@marko-ui/shadcn/ui/button/button.marko"\`), no install
step. Restyle via the \`mu-*\` hook classes in the project's stylesheet; never
edit node_modules.`
    : `marko-ui (<${MARKO_UI_URL}>) — shadcn-style components for Marko 6,
installed as source under \`ui/\`: your files, edit them directly.

Installed: ${
      components.length
        ? components.map((name) => `\`${name}\``).join(", ")
        : "none — run `marko-ui add <name> -y`"
    }`

  const commands = [
    "- `marko-ui docs <name>` — usage, props and examples as markdown. Read it first.",
    "- `marko-ui search -q <query>` — find a component",
    isImport
      ? null
      : "- `marko-ui add <name> -y` — install one",
    "- `marko-ui show <name> --deps` — a component's dependencies",
    "- `marko-ui doctor --json` — project health (exit 3 = a check failed)",
    "- `marko-ui agents sync` — refresh this section and install the agent skills",
  ]
    .filter(Boolean)
    .join("\n")

  return `${AGENTS_START_MARKER}
<!-- Generated by \`marko-ui agents sync\` (v${packageJson.version}). Edits inside these markers are overwritten. -->

## marko-ui components

${intro}

Use the CLI rather than guessing an API or writing a component the registry
ships (\`bunx marko-ui\`):

${commands}

Load the \`marko-ui\` skill before writing component code (\`marko6\` covers Marko
syntax); \`marko-ui agents sync\` installs it.
${AGENTS_END_MARKER}`
}