import { mkdtempSync, mkdirSync, rmSync, writeFileSync } from "fs"
import { tmpdir } from "os"
import path from "path"
import { afterEach, beforeEach, describe, expect, it } from "vitest"

import {
  buildSkillsInstallCommand,
  DEFAULT_SKILLS_SOURCE,
  formatCommand,
  getMissingSkills,
  getSkillsSource,
  selectAgentSkills,
} from "./skills"

describe("selectAgentSkills", () => {
  it("installs the component and language skills everywhere", () => {
    expect(selectAgentSkills("marko-vite")).toEqual(["marko-ui", "marko6"])
    expect(selectAgentSkills("manual")).toEqual(["marko-ui", "marko6"])
    expect(selectAgentSkills(null)).toEqual(["marko-ui", "marko6"])
    expect(selectAgentSkills()).toEqual(["marko-ui", "marko6"])
  })

  it("adds the routing skill only for @marko/run projects", () => {
    expect(selectAgentSkills("marko-run")).toEqual([
      "marko-ui",
      "marko6",
      "marko-run",
    ])
  })

  it("returns a fresh array each call", () => {
    selectAgentSkills("marko-vite").push("mutated")
    expect(selectAgentSkills("marko-vite")).toEqual(["marko-ui", "marko6"])
  })
})

describe("getSkillsSource", () => {
  it("defaults to the marko-ui repo", () => {
    expect(getSkillsSource({})).toBe(DEFAULT_SKILLS_SOURCE)
    expect(DEFAULT_SKILLS_SOURCE).toBe("svallory/marko-ui")
  })

  it("honors an override and ignores an empty one", () => {
    expect(getSkillsSource({ MARKO_UI_SKILLS_SOURCE: "/tmp/checkout" })).toBe(
      "/tmp/checkout"
    )
    expect(getSkillsSource({ MARKO_UI_SKILLS_SOURCE: "" })).toBe(
      DEFAULT_SKILLS_SOURCE
    )
  })
})

describe("buildSkillsInstallCommand", () => {
  const skills = ["marko-ui", "marko6"]

  it("relays to the skills package through bunx", () => {
    const command = buildSkillsInstallCommand("bunx", skills, "svallory/marko-ui")
    expect(command).toEqual({
      file: "bunx",
      args: ["skills", "add", "svallory/marko-ui", "--skill", "marko-ui", "marko6", "-y"],
    })
    expect(formatCommand(command)).toBe(
      "bunx skills add svallory/marko-ui --skill marko-ui marko6 -y"
    )
  })

  it("splits a two-word runner into file and args", () => {
    expect(
      formatCommand(buildSkillsInstallCommand("pnpm dlx", skills, "svallory/marko-ui"))
    ).toBe("pnpm dlx skills add svallory/marko-ui --skill marko-ui marko6 -y")
  })

  it("answers npx's download prompt, which nothing else could", () => {
    const command = buildSkillsInstallCommand("npx", skills, "svallory/marko-ui")
    expect(command.file).toBe("npx")
    expect(command.args.slice(0, 2)).toEqual(["-y", "skills"])
  })

  it("passes every requested skill", () => {
    const command = buildSkillsInstallCommand(
      "bunx",
      ["marko-ui", "marko6", "marko-run"],
      "svallory/marko-ui"
    )
    expect(command.args).toContain("marko-run")
    expect(command.args.at(-1)).toBe("-y")
  })
})

describe("getMissingSkills", () => {
  let cwd: string
  const wanted = ["marko-ui", "marko6"]

  function lock(names: string[]) {
    writeFileSync(
      path.join(cwd, "skills-lock.json"),
      JSON.stringify({
        version: 1,
        skills: Object.fromEntries(
          names.map((name) => [name, { source: "svallory/marko-ui" }])
        ),
      })
    )
  }

  function install(name: string) {
    const dir = path.join(cwd, ".agents/skills", name)
    mkdirSync(dir, { recursive: true })
    writeFileSync(path.join(dir, "SKILL.md"), `---\nname: ${name}\n---\n`)
  }

  beforeEach(() => {
    cwd = mkdtempSync(path.join(tmpdir(), "marko-ui-skills-"))
  })

  afterEach(() => {
    rmSync(cwd, { recursive: true, force: true })
  })

  it("reports everything missing in a project with no lock file", async () => {
    expect(await getMissingSkills(cwd, wanted)).toEqual(wanted)
  })

  it("reports nothing missing when locked and present", async () => {
    lock(wanted)
    wanted.forEach(install)
    expect(await getMissingSkills(cwd, wanted)).toEqual([])
  })

  it("reports only the skill that is absent", async () => {
    lock(["marko6"])
    install("marko6")
    expect(await getMissingSkills(cwd, wanted)).toEqual(["marko-ui"])
  })

  it("does not trust a lock entry whose files are gone", async () => {
    // A fresh clone with .agents/ gitignored: locked, but not on disk.
    lock(wanted)
    install("marko6")
    expect(await getMissingSkills(cwd, wanted)).toEqual(["marko-ui"])
  })

  it("does not count files the skills package did not install", async () => {
    // The skill generated by marko-ui <= 0.4.1 lived under .claude/ with no
    // lock entry; it must be replaced, not mistaken for an install.
    const legacy = path.join(cwd, ".claude/skills/marko-ui")
    mkdirSync(legacy, { recursive: true })
    writeFileSync(path.join(legacy, "SKILL.md"), "legacy")
    install("marko-ui")
    expect(await getMissingSkills(cwd, ["marko-ui"])).toEqual(["marko-ui"])
  })

  it.each([
    ["malformed JSON", "{ not json"],
    ["a lock with no skills key", JSON.stringify({ version: 1 })],
    ["a null lock", "null"],
  ])("treats %s as nothing installed", async (_label, contents) => {
    writeFileSync(path.join(cwd, "skills-lock.json"), contents)
    wanted.forEach(install)
    expect(await getMissingSkills(cwd, wanted)).toEqual(wanted)
  })

  it("has nothing to report when nothing is wanted", async () => {
    expect(await getMissingSkills(cwd, [])).toEqual([])
  })
})
