import { existsSync, promises as fs } from "fs"
import path from "path"
import {
  getPackageManager,
  getPackageRunnerCommand,
} from "@/src/utils/get-package-manager"
import { RegistryErrorCode } from "@/src/registry/errors"
import { getProjectInfo } from "@/src/utils/get-project-info"
import { CommandError } from "@/src/utils/handle-error"
import { highlighter } from "@/src/utils/highlighter"
import { logger } from "@/src/utils/logger"
import { spinner } from "@/src/utils/spinner"
import { execa } from "execa"

/**
 * The agent skills are not generated by this CLI. They live in the repo's
 * `skills/` directory and are installed by the `skills` package
 * (https://skills.sh), which knows every agent's skill directory, records
 * the install in `skills-lock.json`, and updates it with `skills update`.
 * This module only relays to it.
 *
 * It used to be different: `agents sync` wrote a Claude-only
 * `.claude/skills/marko-ui/SKILL.md` built from a template in the CLI. That
 * reached one agent, could not be installed without the CLI, and never
 * appeared in `skills add svallory/marko-ui`.
 */
export const DEFAULT_SKILLS_SOURCE = "svallory/marko-ui"

/**
 * `MARKO_UI_SKILLS_SOURCE` retargets the install at a fork or a local
 * checkout — what the CLI e2e uses, since a skill edited on a branch is
 * not on GitHub yet.
 */
export function getSkillsSource(env: NodeJS.ProcessEnv = process.env) {
  return env.MARKO_UI_SKILLS_SOURCE || DEFAULT_SKILLS_SOURCE
}

/**
 * The exact `skills` release the relay runs. Unpinned, every install would
 * run whatever is latest that day, and a breaking change upstream would break
 * `init --agents` with no change here. Bump it deliberately: check the new
 * release's `add`/`update` flags and `skills-lock.json` format, then update
 * the tests and the docs. It is not a dependency of marko-ui on purpose (no
 * programmatic API, needs `git`, ~42 MB installed); see
 * scratch/team-lead/reports/research-skills-package.md.
 */
export const SKILLS_PACKAGE = "skills@1.7.0"

const BASE_SKILLS = ["marko-ui", "marko6"]

/**
 * `marko-ui` (the CLI workflow and component conventions) and `marko6` (the
 * language, which is what agents get wrong first) always; `marko-run` only
 * where its routing rules apply.
 */
export function selectAgentSkills(frameworkName?: string | null) {
  return frameworkName === "marko-run"
    ? [...BASE_SKILLS, "marko-run"]
    : [...BASE_SKILLS]
}

export function buildSkillsInstallCommand(
  runner: string,
  skills: string[],
  source = getSkillsSource()
) {
  const [file = "npx", ...prefix] = runner.split(" ")
  // npx asks before downloading a package it has not cached; nothing can
  // answer that prompt here, so `-y` answers it.
  const runnerArgs = file === "npx" ? [...prefix, "-y"] : prefix

  return {
    file,
    args: [...runnerArgs, SKILLS_PACKAGE, "add", source, "--skill", ...skills, "-y"],
  }
}

export function formatCommand(command: { file: string; args: string[] }) {
  return [command.file, ...command.args].join(" ")
}

/**
 * The skills from `wanted` that the `skills` package has not installed in
 * this project. Both halves are checked: the lock entry says it was
 * installed, the canonical copy says it is still there (a checkout with
 * `.agents/` gitignored has the first without the second).
 */
export async function getMissingSkills(cwd: string, wanted: string[]) {
  let locked: Record<string, unknown> = {}
  try {
    const lock = JSON.parse(
      await fs.readFile(path.resolve(cwd, "skills-lock.json"), "utf8")
    )
    locked = lock?.skills ?? {}
  } catch {
    // No lock file (or an unreadable one): nothing is installed.
  }

  return wanted.filter(
    (name) =>
      !(name in locked) ||
      !existsSync(path.resolve(cwd, ".agents/skills", name, "SKILL.md"))
  )
}

async function getRunner(cwd: string) {
  return getPackageRunnerCommand(
    await getPackageManager(cwd, { withFallback: true })
  )
}

export async function getWantedSkills(cwd: string) {
  const projectInfo = await getProjectInfo(cwd)
  return selectAgentSkills(projectInfo?.framework?.name)
}

/**
 * Installs the agent skills through the `skills` package. A failure is an
 * error, not a warning: a skipped install is exactly the state that goes
 * unnoticed until an agent has spent a day without the skill.
 */
export async function installAgentSkills(
  cwd: string,
  options: { silent?: boolean } = {}
): Promise<{ installed: string[]; skipped: string[] }> {
  const wanted = await getWantedSkills(cwd)
  const runner = await getRunner(cwd)
  const missing = await getMissingSkills(cwd, wanted)

  if (!missing.length) {
    if (!options.silent) {
      logger.info(
        `Agent skills already installed (${wanted.join(
          ", "
        )}). Update them with ${highlighter.info(`${runner} ${SKILLS_PACKAGE} update`)}.`
      )
    }
    // Reported, not just printed: "were the skills already there?" is the
    // question a program asking about this file actually has, and the
    // "already installed" line was the only answer.
    return { installed: [], skipped: wanted }
  }

  // Ask for every wanted skill, not just the missing ones: `skills add` is
  // idempotent, and one command is what the manual fallback should be.
  const command = buildSkillsInstallCommand(runner, wanted)
  const formatted = formatCommand(command)

  const skillsSpinner = spinner(
    `Installing agent skills (${wanted.join(", ")}): ${formatted}`,
    { silent: options.silent }
  ).start()

  try {
    await execa(command.file, command.args, {
      cwd,
      stdin: "ignore",
      timeout: 180_000,
    })
    skillsSpinner.succeed()
    return { installed: missing, skipped: wanted.filter((s) => !missing.includes(s)) }
  } catch (error) {
    skillsSpinner.fail()
    const reason =
      error instanceof Error
        ? (error.message.split("\n").find((line) => line.trim()) ?? "")
        : String(error)
    // The structured facts go on the ERROR envelope's `details`, not on a
    // `warnings` array: this throws, so there is no successful result to warn
    // inside. That is also why SKILL_INSTALL_FAILED is not a WarningCode — the
    // failure is an error (`MISSING_ENV_VARS`-shaped, exit 1), and a code that
    // could never appear in a `warnings` array was advertising a path the
    // shape does not have.
    throw new CommandError(
      `Could not install the agent skills (${reason}).\nInstall them manually with:\n  ${highlighter.info(
        formatted
      )}\nor pass ${highlighter.info("--no-skill")} to skip them.`,
      {
        code: RegistryErrorCode.SKILL_INSTALL_FAILED,
        suggestion: formatted,
        details: { wanted, command: formatted, reason },
      }
    )
  }
}
