import { MARKO_UI_URL } from "@/src/registry/constants"

import packageJson from "../../package.json"

export const AGENTS_START_MARKER = "<!-- marko-ui:start -->"
export const AGENTS_END_MARKER = "<!-- marko-ui:end -->"

export type InstalledComponent = {
  name: string
  description?: string
}

/**
 * The generated AGENTS.md section. Deliberately small: AGENTS.md is loaded
 * into every agent's context on every task, so it carries only the
 * installed-component index and pointers. Deep content (authoring
 * landmines, CLI recipes) lives in the generated Claude skill, which is
 * loaded on demand.
 */
export function buildAgentsSection(components: InstalledComponent[]) {
  const componentLines = components.length
    ? components
        .map(
          (component) =>
            `- \`${component.name}\`${
              component.description ? ` — ${component.description}` : ""
            }`
        )
        .join("\n")
    : "- (none installed yet — run `marko-ui add`)"

  return `${AGENTS_START_MARKER}
<!-- Generated by \`marko-ui agents sync\` (v${packageJson.version}). Edits inside these markers are overwritten. -->

## marko-ui components

This project uses [marko-ui](${MARKO_UI_URL}) — shadcn-style components for
Marko 6, installed as source under the project's \`ui\` directory. You own
these files; edit them directly rather than wrapping them.

Installed components:

${componentLines}

Working with components:

- \`marko-ui show <name> --props\` — API/props for a component (\`--files\`, \`--deps\` also available)
- \`marko-ui docs <name>\` — full documentation as markdown
- \`marko-ui search -q <query>\` — find more components to install
- \`marko-ui add <name> -y\` — install one (writes source files)
- \`marko-ui doctor --json\` — verify project health

Marko 6 has authoring pitfalls that break these components in non-obvious
ways (controlled props, boolean attributes, typed \`<let>\`). Before writing
or editing component code, read the marko-ui skill if available
(\`.claude/skills/marko-ui/SKILL.md\`) or run \`marko-ui docs <component>\`.
${AGENTS_END_MARKER}`
}

/**
 * The generated Claude skill: on-demand deep content. Curated here (in the
 * CLI, versioned with it) because the authoring-landmines catalog has no
 * distributable canonical source yet — the docs site's creating-components
 * page has no markdown endpoint. Revisit when it does.
 */
export function buildSkill(components: InstalledComponent[]) {
  const names = components.map((component) => component.name).join(", ")

  return `---
name: marko-ui
description: Use when writing or editing marko-ui components, Marko 6 templates that use them, or when installing/inspecting components from the marko-ui registry.
---

# Working with marko-ui

marko-ui components are Zag-machine-backed Marko 6 components installed AS
SOURCE into this project${names ? ` (installed: ${names})` : ""}. You own
the files — edit them directly.

## CLI workflow

1. \`marko-ui search -q <query>\` — find components (add \`--json\` for machine output)
2. \`marko-ui show <name> --props\` — inspect the API before using a component
3. \`marko-ui add <name> -y\` — install; \`--dry-run\` previews, \`diff <name>\` compares local edits against the registry
4. \`marko-ui doctor --json\` — exit code 3 means something is broken; each check names the fix

## Marko 6 authoring landmines

These have each caused real bugs in this codebase. Check code against this
list before finishing.

1. **Controlled props pin the machine.** Passing \`open=\` / \`value=\` WITHOUT
   the matching \`openChange\`/\`valueChange\` handler freezes the component in
   that state. Want an initial value only? Use \`defaultOpen=\` /
   \`defaultValue=\`.
2. **Boolean aria-*/data-* attributes serialize wrong.** Marko renders
   boolean \`true\` as a bare attribute: \`aria-selected=(bool)\` emits
   \`aria-selected=""\` (incorrect for a11y) and \`data-active=(bool)\` never
   matches \`data-[active=true]:\` Tailwind variants. Wrap in \`String(...)\`.
3. **\`key=\` is not a Marko attribute.** Use \`<for|item| of=items by=(item) => item.id>\`.
4. **Typed \`<let>\` needs a cast, not an annotation.**
   \`<let/value = null as string | null>\` — union annotations on \`<let>\`
   don't parse.
5. **\`<html-script>\` vs \`<script>\`.** A bare \`<script>\` tag in Marko 6 is
   the component's client script block. To emit an actual HTML script tag
   (e.g. the no-flash theme snippet), use \`<html-script>\`.
6. **Ambiguous \`>\` in attribute expressions.** Comparisons or arrow
   functions inside attributes need parentheses:
   \`disabled=(count > 3)\`, \`onClick=(() => doThing())\`.
7. **Bind shorthand is for value props only.** \`value:=state\` style
   two-way binding applies to value-like props, not arbitrary attributes.
8. **Server/client serialization boundary.** Values crossing from server to
   client sections must be serializable — Zag machine getters and class
   instances are not; pass plain data and reconnect on the client.
9. **Imports use the \`marko-zag\` adapter package.** Component source
   imports \`MachineInput\` types and machine wiring from \`"marko-zag"\`
   (docs: https://marko-zag.saulo.tech). If it is missing, installs still
   work but the import fails at build time — \`marko-ui doctor\` reports
   any missing component dependencies.

## Component anatomy

Zag-backed components follow the three-tag pattern: \`<machine-props>\`
(typed input), \`<service>\` (machine lifecycle), \`<connect>\` (API → DOM
props). Sub-parts live one directory per component
(\`ui/<name>/<part>.marko\`). Styling comes from \`variants.ts\`
(class-variance-authority) + Tailwind v4 CSS variables in globals.css.

## More documentation

- \`marko-ui docs <component>\` — per-component markdown (props, usage, examples)
- ${MARKO_UI_URL}/docs/creating-components — the full authoring guide
`
}
