import { defineConfig, type Plugin } from "vite"
import react from "@vitejs/plugin-react"
import tailwindcss from "@tailwindcss/vite"
import { existsSync, readdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join, relative } from "node:path"
import { resolveShadcnClone } from "../upstream-shadcn.ts"

const HERE = dirname(fileURLToPath(import.meta.url))
const GENERATED_DIR = join(HERE, ".generated")

/**
 * Tailwind's `@source` directive needs a literal relative path baked into
 * the CSS at build time, but the upstream clone's actual location is only
 * known once resolveShadcnClone() runs (env var / hyperspace sibling /
 * repo-local .upstream/ — see tooling/upstream-shadcn.ts). Write it into a
 * small generated, gitignored CSS file that src/main.css @imports, so
 * main.css itself stays static and portable across machines.
 *
 * Sources both the raw registry/bases/base/ui tree (for classes outside
 * the cn-* style-map, e.g. layout utilities the demo/example files author
 * directly) and this harness's own .generated/styles output (for the
 * style-transformed cn-* replacements — see generate-styled-registry.ts).
 */
function writeGeneratedSourceCss(cloneRoot: string): void {
  const basesDir = join(cloneRoot, "apps", "v4", "registry", "bases")
  const examplesDir = join(cloneRoot, "apps", "v4", "examples")
  const basesRel = relative(join(HERE, "src"), basesDir).split("\\").join("/")
  const examplesRel = relative(join(HERE, "src"), examplesDir).split("\\").join("/")
  const generatedRel = relative(join(HERE, "src"), GENERATED_DIR).split("\\").join("/")
  writeFileSync(
    join(HERE, "src", "generated-source.css"),
    `/* GENERATED by vite.config.ts — do not edit, do not commit. */\n` +
      `@source "${basesRel}/**/*.tsx";\n` +
      `@source "${examplesRel}/**/*.tsx";\n` +
      `@source "${generatedRel}/**/*.tsx";\n`
  )
}

/**
 * Resolve the upstream shadcn/ui clone the same way the rest of tooling/
 * does (SHADCN_UI_DIR env, hyperspace sibling, or repo-local .upstream/).
 * The harness renders demos and ui/* components straight from this clone's
 * `apps/v4/registry/bases/base` + `apps/v4/examples/base` trees, style-
 * transformed per-component into this harness's own `.generated/styles`
 * (see generate-styled-registry.ts and PROTOCOL.md's "Style pairing") —
 * there is no vendored copy — so the clone must already exist (`bun
 * tooling/parity/harness-react` never clones on its own; run
 * `check:parity` once first, or set SHADCN_UI_DIR).
 */
const cloneRoot = resolveShadcnClone()
if (!cloneRoot) {
  throw new Error(
    "harness-react/vite.config.ts: no upstream shadcn/ui clone found. " +
      "Set SHADCN_UI_DIR or run the shadcn harness's extract step once to " +
      "auto-clone (bun tooling/parity/harnesses/shadcn/extract/index.ts)."
  )
}

const v4Root = join(cloneRoot, "apps", "v4")
const v4NodeModules = join(v4Root, "node_modules")
const cloneNodeModules = join(cloneRoot, "node_modules")
if (!existsSync(v4NodeModules) && !existsSync(cloneNodeModules)) {
  throw new Error(
    `harness-react/vite.config.ts: neither ${v4NodeModules} nor ${cloneNodeModules} ` +
      "exist — the clone's own dependencies (@base-ui/react, sonner, " +
      "lucide-react, ...) must be installed before the harness can alias " +
      "into them."
  )
}

/** Resolve a package by name straight out of the clone's own node_modules
 * (apps/v4's local node_modules first, falling back to the repo-root
 * hoisted node_modules — bun/pnpm workspaces hoist most deps there). */
function fromClone(pkg: string): string {
  const local = join(v4NodeModules, pkg)
  return existsSync(local) ? local : join(cloneNodeModules, pkg)
}

writeGeneratedSourceCss(cloneRoot)

/**
 * The style-transformed component trees this harness's demos import from
 * (`@/styles/base-nova/ui/*`, `@/styles/base-rhea/ui/*`,
 * `@/styles/base-nova/ui-rtl/*`) are materialized by
 * generate-styled-registry.ts, run as a `bun` prestep from package.json
 * (`predev`/`prebuild`/`prepreview`) BEFORE vite starts — not called
 * inline here, because Vite resolves this config file under Node's ESM
 * loader even when invoked via `bun run`, and Node cannot follow the
 * upstream clone's extensionless internal TS imports the way bun's
 * resolver can (see that script's own header comment). This just asserts
 * the prestep already ran.
 */
if (!existsSync(GENERATED_DIR)) {
  throw new Error(
    `harness-react/vite.config.ts: ${GENERATED_DIR} is missing — run ` +
      "`bun generate-styled-registry.ts` (or `bun run dev`/`build`/" +
      "`preview`, which do this automatically via their `pre*` scripts) " +
      "before starting Vite."
  )
}

/**
 * Virtual module exposing every upstream example basename -> lazy import,
 * so App.tsx's demo router doesn't need a compile-time-static glob string
 * pointed at a clone path whose location varies by machine (env var /
 * hyperspace sibling / repo-local .upstream/ — see resolveShadcnClone).
 * The generated code below IS a static glob string, just built once here
 * with the already-resolved absolute clone path baked in.
 */
function demoRegistryPlugin(examplesDir: string): Plugin {
  const virtualId = "virtual:demo-registry"
  const resolvedId = "\0" + virtualId
  return {
    name: "parity-demo-registry",
    resolveId(id) {
      if (id === virtualId) return resolvedId
    },
    load(id) {
      if (id !== resolvedId) return
      const names = readdirSync(examplesDir)
        .filter((entry) => entry.endsWith(".tsx"))
        .map((entry) => entry.slice(0, -".tsx".length))
        .sort()
      const entries = names
        .map((name) => `  ${JSON.stringify(name)}: () => import(${JSON.stringify(join(examplesDir, `${name}.tsx`))}),`)
        .join("\n")
      return `export const demoLoaders = {\n${entries}\n}\n`
    },
  }
}

export default defineConfig({
  root: HERE,
  plugins: [
    react(),
    tailwindcss(),
    demoRegistryPlugin(join(v4Root, "examples", "base")),
  ],
  resolve: {
    alias: [
      // Style-transformed component trees (see generate-styled-registry.ts)
      // — must come before the raw @/registry alias below since both
      // start with "@/" and Vite matches in array order.
      //
      // The style suffix is forced to "-nova" here, in the alias's own
      // `find` regex + `customResolver`, rather than in a separate
      // resolveId-hook plugin: Vite's `resolve.alias` array is consumed by
      // an internal alias-resolution plugin that runs before any
      // ordinary user plugin's resolveId (regardless of `enforce: "pre"`
      // on that plugin) — a standalone plugin never actually saw these
      // specifiers in testing. Folding the rewrite into the alias itself
      // sidesteps that ordering entirely. See PROTOCOL.md's "Style
      // pairing": comparisons run in the TARGET port's declared default
      // style (marko-ui's docs site is always style-nova, globally, with
      // no per-component override) — never whichever style a given
      // upstream showcase page happens to have chosen for that one
      // component (drawer.mdx declares base-rhea, most others base-nova).
      // Only the `<base>` prefix (base/radix/aria) is preserved from the
      // demo's own import; the trailing `-<style>` suffix is always
      // rewritten to `-nova`.
      {
        // Rollup's alias plugin applies `replacement`'s $1/$2 substitution
        // BEFORE calling `customResolver` — customResolver receives the
        // already-substituted string (e.g. "base/ui/accordion" or just
        // "base"), not the original `@/styles/...` specifier. $1 = base
        // name (base/radix/aria), $2 = the rest of the path including its
        // leading slash, or "" when the bare style root itself was
        // imported (no trailing path segment).
        find: /^@\/styles\/(base|radix|aria)-[a-z]+(\/.*)?$/,
        replacement: "$1\0$2",
        async customResolver(substituted, importer, options) {
          const [baseName, rest] = substituted.split("\0")
          const forcedPath = join(GENERATED_DIR, `${baseName}-nova`, ...(rest ? [rest.slice(1)] : []))
          // Delegate to the normal resolver for extension resolution
          // (.tsx/.ts/index.tsx/...) — a bare fs path here would otherwise
          // be read literally with no extension, which never exists on
          // disk (every generated file keeps its .tsx extension).
          return this.resolve(forcedPath, importer, { ...options, skipSelf: true })
        },
      },

      // The example .tsx files and registry ui/*.tsx files import
      // "@/registry/...", "@/components/...", and "@/lib/utils" per the
      // clone's own tsconfig paths convention — point those straight at
      // the clone so the demo source is used completely unmodified.
      { find: "@/components", replacement: join(v4Root, "components") },
      // IconPlaceholder shim (see src/shims/icon-placeholder.tsx) — must
      // come before the broader @/app/(create) alias below since both
      // match "@/app/(create)/components/icon-placeholder" as a prefix
      // and Vite's alias array matches in order.
      { find: "@/app/(create)/components/icon-placeholder", replacement: join(HERE, "src/shims/icon-placeholder.tsx") },
      // Temp aliases the clone's own tsconfig.json declares (registry
      // sources import @/app/(create)/* verbatim, ships in published
      // registry payloads) — the files actually live under
      // app/(app)/(create)/*. Mirrored here for the same reason.
      { find: "@/app/(create)", replacement: join(v4Root, "app", "(app)", "(create)") },
      { find: "@/app/(app)/(create)", replacement: join(v4Root, "app", "(app)", "(create)") },
      { find: "@/registry", replacement: join(v4Root, "registry") },
      { find: "@/lib/utils", replacement: join(v4Root, "lib", "utils.ts") },
      { find: "@/lib", replacement: join(v4Root, "lib") },
      { find: "@/hooks", replacement: join(v4Root, "hooks") },

      // Next-specific imports the example files use: shimmed with plain
      // DOM/React equivalents (see src/shims/).
      { find: "next/image", replacement: join(HERE, "src/shims/next-image.tsx") },
      { find: "next/link", replacement: join(HERE, "src/shims/next-link.tsx") },
      { find: "next/font/google", replacement: join(HERE, "src/shims/next-font-google.ts") },
      { find: "next-themes", replacement: join(HERE, "src/shims/next-themes.tsx") },

      // Runtime deps the demos/ui pull in: resolved from the clone's own
      // node_modules (already pnpm-installed there) rather than
      // reinstalling the whole dependency graph in this harness, so the
      // exact same versions upstream renders with are the ones we render
      // with too.
      { find: "react", replacement: fromClone("react") },
      { find: "react-dom", replacement: fromClone("react-dom") },
      { find: "@base-ui/react", replacement: fromClone("@base-ui/react") },
      { find: "radix-ui", replacement: fromClone("radix-ui") },
      { find: "vaul", replacement: fromClone("vaul") },
      { find: "lucide-react", replacement: fromClone("lucide-react") },
      { find: "class-variance-authority", replacement: fromClone("class-variance-authority") },
      { find: "clsx", replacement: fromClone("clsx") },
      { find: "tailwind-merge", replacement: fromClone("tailwind-merge") },
      { find: "recharts", replacement: fromClone("recharts") },
      { find: "sonner", replacement: fromClone("sonner") },
      { find: "streamdown", replacement: fromClone("streamdown") },
      { find: "@streamdown/code", replacement: fromClone("@streamdown/code") },
      { find: "@ai-sdk/react", replacement: fromClone("@ai-sdk/react") },
      { find: "@hugeicons/core-free-icons", replacement: fromClone("@hugeicons/core-free-icons") },
      { find: "@hugeicons/react", replacement: fromClone("@hugeicons/react") },
      // @shadcn/helpers and @shadcn/react are subpath-exports-only packages
      // (package.json "exports" has no "." entry, only "./ai-sdk" etc.) —
      // aliasing the bare specifier would make Vite treat
      // "@shadcn/helpers/ai-sdk" as a literal path under the aliased dir,
      // bypassing the exports map entirely. Alias each subpath actually
      // used instead, straight at its resolved dist file.
      {
        find: "@shadcn/helpers/ai-sdk",
        replacement: join(cloneRoot, "packages", "helpers", "dist", "ai-sdk", "index.js"),
      },
      {
        find: "@shadcn/helpers/tanstack-ai",
        replacement: join(cloneRoot, "packages", "helpers", "dist", "tanstack-ai", "index.js"),
      },
      {
        find: "@shadcn/react/message-scroller",
        replacement: join(cloneRoot, "packages", "react", "dist", "message-scroller", "index.js"),
      },
      {
        find: "@shadcn/react/questionnaire",
        replacement: join(cloneRoot, "packages", "react", "dist", "questionnaire", "index.js"),
      },
      { find: "@tabler/icons-react", replacement: fromClone("@tabler/icons-react") },
      // @tanstack/ai-client has both a "." and a "./devtools" export;
      // aliasing the bare specifier breaks the "./devtools" subpath the
      // same way @shadcn/helpers did above (see comment there) — alias
      // both explicitly instead.
      {
        find: "@tanstack/ai-client/devtools",
        replacement: join(v4NodeModules, "@tanstack/ai-client/dist/esm/devtools.js"),
      },
      { find: "@tanstack/ai-client", replacement: fromClone("@tanstack/ai-client") },
      { find: "@tanstack/ai-react", replacement: fromClone("@tanstack/ai-react") },
      { find: "@vercel/analytics", replacement: fromClone("@vercel/analytics") },
      { find: "chrono-node", replacement: fromClone("chrono-node") },
      { find: "cmdk", replacement: fromClone("cmdk") },
      { find: "date-fns", replacement: fromClone("date-fns") },
      { find: "embla-carousel-autoplay", replacement: fromClone("embla-carousel-autoplay") },
      { find: "embla-carousel-react", replacement: fromClone("embla-carousel-react") },
      { find: "fumadocs-core", replacement: fromClone("fumadocs-core") },
      { find: "input-otp", replacement: fromClone("input-otp") },
      { find: "lodash", replacement: fromClone("lodash") },
      { find: "motion", replacement: fromClone("motion") },
      { find: "react-aria-components", replacement: fromClone("react-aria-components") },
      { find: "react-day-picker", replacement: fromClone("react-day-picker") },
      { find: "react-resizable-panels", replacement: fromClone("react-resizable-panels") },
      { find: "react-textarea-autosize", replacement: fromClone("react-textarea-autosize") },
      // shadcn (the CLI package) is subpath-exports-only for everything
      // except "." itself — same rationale as @shadcn/helpers above.
      { find: "shadcn/registry", replacement: join(cloneRoot, "packages", "shadcn", "dist", "registry", "index.js") },
      { find: "shadcn/schema", replacement: join(cloneRoot, "packages", "shadcn", "dist", "schema", "index.js") },
      { find: "shadcn/mcp", replacement: join(cloneRoot, "packages", "shadcn", "dist", "mcp", "index.js") },
      { find: "shadcn/utils", replacement: join(cloneRoot, "packages", "shadcn", "dist", "utils", "index.js") },
      { find: "shadcn/icons", replacement: join(cloneRoot, "packages", "shadcn", "dist", "icons", "index.js") },
      { find: "shadcn/preset", replacement: join(cloneRoot, "packages", "shadcn", "dist", "preset", "index.js") },
      { find: "shadcn/tailwind.css", replacement: join(cloneRoot, "packages", "shadcn", "dist", "tailwind.css") },
      { find: "shadcn", replacement: join(cloneRoot, "packages", "shadcn", "dist", "index.js") },
      { find: "zod", replacement: fromClone("zod") },
      // next/navigation, next/script: additional Next-specific imports
      // beyond next/image, next/link, next/font/google (already shimmed
      // above) that the fuller registry/bases/base + examples/base trees
      // pull in — no-op shims, same rationale as the others.
      { find: "next/navigation", replacement: join(HERE, "src/shims/next-navigation.tsx") },
      { find: "next/script", replacement: join(HERE, "src/shims/next-script.tsx") },
    ],
  },
  server: {
    port: 4174,
    strictPort: true,
  },
  preview: {
    port: 4174,
    strictPort: true,
  },
  build: {
    outDir: join(HERE, "dist"),
  },
})
