import { defineConfig, type Plugin } from "vite"
import react from "@vitejs/plugin-react"
import tailwindcss from "@tailwindcss/vite"
import { existsSync, readdirSync, writeFileSync } from "node:fs"
import { fileURLToPath } from "node:url"
import { dirname, join, relative } from "node:path"
import { resolveShadcnClone } from "../upstream-shadcn.ts"

const HERE = dirname(fileURLToPath(import.meta.url))

/**
 * Tailwind's `@source` directive needs a literal relative path baked into
 * the CSS at build time, but the upstream clone's actual location is only
 * known once resolveShadcnClone() runs (env var / hyperspace sibling /
 * repo-local .upstream/ — see tooling/upstream-shadcn.ts). Write it into a
 * small generated, gitignored CSS file that src/main.css @imports, so
 * main.css itself stays static and portable across machines.
 */
function writeGeneratedSourceCss(cloneRoot: string): void {
  const registryDir = join(cloneRoot, "apps", "v4", "registry", "new-york-v4")
  const relPath = relative(join(HERE, "src"), registryDir).split("\\").join("/")
  writeFileSync(
    join(HERE, "src", "generated-source.css"),
    `/* GENERATED by vite.config.ts — do not edit, do not commit. */\n@source "${relPath}/**/*.tsx";\n`
  )
}

/**
 * Resolve the upstream shadcn/ui clone the same way the rest of tooling/
 * does (SHADCN_UI_DIR env, hyperspace sibling, or repo-local .upstream/).
 * The harness renders demos and ui/* components straight from this clone's
 * `apps/v4/registry/new-york-v4` tree — there is no vendored copy — so the
 * clone must already exist (`bun tooling/parity/harness-react` never
 * clones on its own; run `check:parity` once first, or set SHADCN_UI_DIR).
 */
const cloneRoot = resolveShadcnClone()
if (!cloneRoot) {
  throw new Error(
    "harness-react/vite.config.ts: no upstream shadcn/ui clone found. " +
      "Set SHADCN_UI_DIR or run the shadcn harness's extract step once to " +
      "auto-clone (bun tooling/parity/harnesses/shadcn/extract/index.ts)."
  )
}

const v4Root = join(cloneRoot, "apps", "v4")
const v4NodeModules = join(v4Root, "node_modules")
if (!existsSync(v4NodeModules)) {
  throw new Error(
    `harness-react/vite.config.ts: ${v4NodeModules} is missing — the clone's ` +
      "own dependencies (radix-ui, vaul, recharts, ...) must be installed " +
      "there (pnpm install in the clone) before the harness can alias into them."
  )
}

/** Resolve a package by name straight out of the clone's own node_modules. */
function fromClone(pkg: string): string {
  return join(v4NodeModules, pkg)
}

writeGeneratedSourceCss(cloneRoot)

/**
 * Virtual module exposing every upstream example basename -> lazy import,
 * so App.tsx's demo router doesn't need a compile-time-static glob string
 * pointed at a clone path whose location varies by machine (env var /
 * hyperspace sibling / repo-local .upstream/ — see resolveShadcnClone).
 * The generated code below IS a static glob string, just built once here
 * with the already-resolved absolute clone path baked in.
 */
function demoRegistryPlugin(examplesDir: string): Plugin {
  const virtualId = "virtual:demo-registry"
  const resolvedId = "\0" + virtualId
  return {
    name: "parity-demo-registry",
    resolveId(id) {
      if (id === virtualId) return resolvedId
    },
    load(id) {
      if (id !== resolvedId) return
      const names = readdirSync(examplesDir)
        .filter((entry) => entry.endsWith(".tsx"))
        .map((entry) => entry.slice(0, -".tsx".length))
        .sort()
      const entries = names
        .map((name) => `  ${JSON.stringify(name)}: () => import(${JSON.stringify(join(examplesDir, `${name}.tsx`))}),`)
        .join("\n")
      return `export const demoLoaders = {\n${entries}\n}\n`
    },
  }
}

export default defineConfig({
  root: HERE,
  plugins: [
    react(),
    tailwindcss(),
    demoRegistryPlugin(join(v4Root, "registry", "new-york-v4", "examples")),
  ],
  resolve: {
    alias: [
      // The demo .tsx files and registry ui/*.tsx files import
      // "@/registry/..." and "@/lib/utils" per the clone's own tsconfig
      // paths convention — point those straight at the clone so the demo
      // source is used completely unmodified.
      { find: "@/registry", replacement: join(v4Root, "registry") },
      { find: "@/lib/utils", replacement: join(v4Root, "lib", "utils.ts") },
      { find: "@/lib", replacement: join(v4Root, "lib") },
      { find: "@/hooks", replacement: join(v4Root, "hooks") },

      // Next-specific imports the example files use: shimmed with plain
      // DOM/React equivalents (see src/shims/).
      { find: "next/image", replacement: join(HERE, "src/shims/next-image.tsx") },
      { find: "next/link", replacement: join(HERE, "src/shims/next-link.tsx") },
      { find: "next/font/google", replacement: join(HERE, "src/shims/next-font-google.ts") },
      { find: "next-themes", replacement: join(HERE, "src/shims/next-themes.tsx") },

      // Runtime deps the demos/ui pull in: resolved from the clone's own
      // node_modules (already pnpm-installed there) rather than
      // reinstalling the whole dependency graph in this harness, so the
      // exact same versions upstream renders with are the ones we render
      // with too.
      { find: "react", replacement: fromClone("react") },
      { find: "react-dom", replacement: fromClone("react-dom") },
      { find: "radix-ui", replacement: fromClone("radix-ui") },
      { find: "vaul", replacement: fromClone("vaul") },
      { find: "lucide-react", replacement: fromClone("lucide-react") },
      { find: "class-variance-authority", replacement: fromClone("class-variance-authority") },
      { find: "clsx", replacement: fromClone("clsx") },
      { find: "tailwind-merge", replacement: fromClone("tailwind-merge") },
      { find: "recharts", replacement: fromClone("recharts") },
    ],
  },
  server: {
    port: 4174,
    strictPort: true,
  },
  preview: {
    port: 4174,
    strictPort: true,
  },
  build: {
    outDir: join(HERE, "dist"),
  },
})
