/**
 * Input type for a component wrapping a Zag machine: native tag attributes
 * intersected with the machine's full Props — the only adjustment is `id`,
 * required by Zag's CommonProperties but generated by <machine-props>
 * (consumers may still override it).
 *
 *   export type Input = MachineInput<"input", switchMachine.Props> & {
 *     checkedChange?: (checked: boolean) => void; // Marko bind-shorthand sugar
 *   };
 */
export type MachineInput<Tag, Props> = Marko.Input<Tag> &
  Omit<Props, "id"> & { id?: string };
