// GENERATED by apps/docs/scripts/build-cli-manifest.ts — do not edit.
// Rebuild with: bun apps/docs/scripts/build-cli-manifest.ts

export type CliOption = {
  flags: string;
  description: string;
  defaultValue?: unknown;
};

export type CliArgument = {
  name: string;
  required: boolean;
  variadic: boolean;
  description?: string;
};

export type CliCommand = {
  name: string;
  aliases: string[];
  description: string;
  arguments: CliArgument[];
  options: CliOption[];
  subcommands?: CliCommand[];
};

export type CliManifest = {
  cliVersion: string;
  commands: CliCommand[];
  exitCodes: Record<string, string>;
  /** Stable machine-readable warning codes, next to the error codes in the
   *  CLI's own manifest. Carried here so the docs page can list one
   *  vocabulary for both outcomes. */
  warningCodes?: string[];
  agentWorkflow: string[];
};

export const CLI_MANIFEST: CliManifest = {
  "cliVersion": "0.6.0",
  "commands": [
    {
      "name": "init",
      "aliases": [],
      "description": "initialize your project and install dependencies",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "names, url or local path to component"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "-y, --yes",
          "description": "do not prompt; use the default for every choice not given by flag (base color, distribution, visual style)."
        },
        {
          "flags": "-d, --defaults",
          "description": "do not prompt; use the default for every choice not given by flag. same as --yes."
        },
        {
          "flags": "-f, --force",
          "description": "force overwrite of existing configuration.",
          "defaultValue": false
        },
        {
          "flags": "-s, --silent",
          "description": "mute output. also disables prompts (defaults are used).",
          "defaultValue": false
        },
        {
          "flags": "-b, --base-color <name>",
          "description": "the base color to use."
        },
        {
          "flags": "--css-variables",
          "description": "use css variables for theming.",
          "defaultValue": true
        },
        {
          "flags": "--no-css-variables",
          "description": "do not use css variables for theming."
        },
        {
          "flags": "--agents",
          "description": "also write the marko-ui section of AGENTS.md and install the agent skills. safe to run on an already-initialized project.",
          "defaultValue": false
        },
        {
          "flags": "-D, --distribution <mode>",
          "description": "how components are shipped: copy (flat generated source, default) or import (@marko-ui/shadcn hook-class components + CSS layers)."
        },
        {
          "flags": "--visual-style <name>",
          "description": "the visual style to use (rhea, nova, vega, lyra, maia, mira, luma, sera, new-york). selects the generated source for copy, and the precompiled CSS layer for import."
        },
        {
          "flags": "--json",
          "description": "output as JSON (the choices made, the files written, and any warnings).",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "add",
      "aliases": [],
      "description": "add a component to your project",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "item addresses to add"
        }
      ],
      "options": [
        {
          "flags": "-y, --yes",
          "description": "skip confirmation prompt.",
          "defaultValue": false
        },
        {
          "flags": "-o, --overwrite",
          "description": "overwrite existing files.",
          "defaultValue": false
        },
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "-a, --all",
          "description": "add all available components",
          "defaultValue": false
        },
        {
          "flags": "-p, --path <path>",
          "description": "the path to add the component to."
        },
        {
          "flags": "-s, --silent",
          "description": "mute output.",
          "defaultValue": false
        },
        {
          "flags": "--dry-run",
          "description": "preview changes without writing files.",
          "defaultValue": false
        },
        {
          "flags": "--json",
          "description": "output as JSON (what was written, and any warnings).",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "diff",
      "aliases": [],
      "description": "show diffs between local files and their registry versions",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "component names (defaults to all installed)"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "--name-only",
          "description": "only list files that differ.",
          "defaultValue": false
        },
        {
          "flags": "--json",
          "description": "output as JSON (per file status, and diffs for changed ones).",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "docs",
      "aliases": [],
      "description": "print component documentation as markdown",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "component names (e.g. button dialog)"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "-l, --list",
          "description": "list documented components.",
          "defaultValue": false
        },
        {
          "flags": "--json",
          "description": "output as JSON (with --list, or the markdown itself).",
          "defaultValue": false
        },
        {
          "flags": "--examples",
          "description": "print every example instead of the essential ones.",
          "defaultValue": false
        },
        {
          "flags": "--example <id...>",
          "description": "print only the named examples. Every id is listed in the \"More examples\" section of the default output."
        },
        {
          "flags": "--remote",
          "description": "read the docs from the registry even for an installed component (default: the installed version's docs).",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "show",
      "aliases": [
        "view"
      ],
      "description": "show items from the registry (files, dependencies, source)",
      "arguments": [
        {
          "name": "items",
          "required": true,
          "variadic": true,
          "description": "item addresses to view"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "--files",
          "description": "only list file paths.",
          "defaultValue": false
        },
        {
          "flags": "--deps",
          "description": "only list npm and registry dependencies.",
          "defaultValue": false
        },
        {
          "flags": "--json",
          "description": "no-op: show always prints JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "search",
      "aliases": [
        "list"
      ],
      "description": "search items from registries",
      "arguments": [
        {
          "name": "registries",
          "required": false,
          "variadic": true,
          "description": "the registry addresses to search. Supports namespaces, GitHub sources and URLs. When omitted, searches all registries configured in components.json."
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "-q, --query <query>",
          "description": "query string"
        },
        {
          "flags": "-t, --type <type>",
          "description": "filter by item type, e.g. ui, block, hook. Comma-separated for multiple."
        },
        {
          "flags": "-l, --limit <number>",
          "description": "maximum number of items to display",
          "defaultValue": "100"
        },
        {
          "flags": "-o, --offset <number>",
          "description": "number of items to skip",
          "defaultValue": "0"
        },
        {
          "flags": "--json",
          "description": "output as JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "status",
      "aliases": [
        "info"
      ],
      "description": "get information about your project",
      "arguments": [],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "--json",
          "description": "output as JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "doctor",
      "aliases": [],
      "description": "check the health of your marko-ui setup",
      "arguments": [],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "--json",
          "description": "output as JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "eject",
      "aliases": [],
      "description": "switch this project from the import distribution (@marko-ui/shadcn) to copy: fetch and write local component source for everything currently installed",
      "arguments": [],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "current working directory"
        },
        {
          "flags": "-y, --yes",
          "description": "skip confirmation prompt.",
          "defaultValue": false
        },
        {
          "flags": "-s, --silent",
          "description": "mute output.",
          "defaultValue": false
        },
        {
          "flags": "--json",
          "description": "output as JSON (files written, and any manual steps left).",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "manifest",
      "aliases": [],
      "description": "describe the CLI, or one command, as machine-readable JSON",
      "arguments": [
        {
          "name": "command",
          "required": false,
          "variadic": false,
          "description": "describe only this command (name or alias)"
        }
      ],
      "options": []
    },
    {
      "name": "agents",
      "aliases": [],
      "description": "set up and refresh what AI coding agents need in this project",
      "arguments": [],
      "options": [],
      "subcommands": [
        {
          "name": "sync",
          "aliases": [],
          "description": "write the marko-ui section of AGENTS.md and install the agent skills",
          "arguments": [],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "current working directory"
            },
            {
              "flags": "--check",
              "description": "fail (exit 3) if AGENTS.md is stale or the agent skills are not installed.",
              "defaultValue": false
            },
            {
              "flags": "--no-skill",
              "description": "do not install (or check) the agent skills; AGENTS.md only."
            },
            {
              "flags": "-s, --silent",
              "description": "mute output.",
              "defaultValue": false
            },
            {
              "flags": "--json",
              "description": "output as JSON (whether AGENTS.md changed, and which skills were installed).",
              "defaultValue": false
            }
          ]
        }
      ]
    },
    {
      "name": "registry",
      "aliases": [],
      "description": "manage registries",
      "arguments": [],
      "options": [],
      "subcommands": [
        {
          "name": "list",
          "aliases": [],
          "description": "list configured registries and the marko-ui registry index",
          "arguments": [],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "current working directory"
            },
            {
              "flags": "--json",
              "description": "output as JSON.",
              "defaultValue": false
            },
            {
              "flags": "--index-only",
              "description": "only show registries from the index.",
              "defaultValue": false
            }
          ]
        },
        {
          "name": "add",
          "aliases": [],
          "description": "add registries to your project",
          "arguments": [
            {
              "name": "registries",
              "required": false,
              "variadic": true,
              "description": "registries (@namespace) or registry URLs (@namespace=url)"
            }
          ],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "current working directory"
            },
            {
              "flags": "-s, --silent",
              "description": "mute output.",
              "defaultValue": false
            }
          ]
        },
        {
          "name": "remove",
          "aliases": [],
          "description": "remove registries from your project",
          "arguments": [
            {
              "name": "registries",
              "required": true,
              "variadic": true,
              "description": "registry namespaces to remove (e.g. @acme)"
            }
          ],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "current working directory"
            },
            {
              "flags": "-s, --silent",
              "description": "mute output.",
              "defaultValue": false
            }
          ]
        },
        {
          "name": "validate",
          "aliases": [],
          "description": "validate a registry against the registry item schema",
          "arguments": [
            {
              "name": "registry",
              "required": false,
              "variadic": false,
              "description": "registry address to validate. Supports registry.json paths and GitHub sources."
            }
          ],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "current working directory"
            }
          ]
        },
        {
          "name": "build",
          "aliases": [],
          "description": "build registry.json into installable registry item files",
          "arguments": [
            {
              "name": "registry",
              "required": false,
              "variadic": false,
              "description": "path to registry.json file"
            }
          ],
          "options": [
            {
              "flags": "-o, --output <path>",
              "description": "destination directory for json files",
              "defaultValue": "./public/r"
            },
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "current working directory"
            },
            {
              "flags": "-v, --verbose",
              "description": "verbose output"
            }
          ]
        }
      ]
    }
  ],
  "exitCodes": {
    "0": "success",
    "1": "operational failure",
    "2": "usage error (unknown command/option, bad arguments)",
    "3": "doctor/validate/agents-check found problems",
    "4": "network error or registry unreachable (registry-backed commands)"
  },
  "warningCodes": [
    "TS_ALLOW_IMPORTING_EXTENSIONS",
    "LAYOUT_NOT_FOUND",
    "DEPENDENCY_INSTALL_FAILED",
    "ITEM_HAS_DOCS",
    "MANUAL_STEPS_REMAIN",
    "PROJECT_NOT_INITIALIZED",
    "STALE_FILES_REMOVED"
  ],
  "agentWorkflow": [
    "marko-ui search -q <query> — find items across configured registries",
    "marko-ui show <item> — inspect an item (add --files or --deps to narrow)",
    "marko-ui docs <item> — full component documentation as markdown",
    "marko-ui add <item> -y — install it",
    "marko-ui doctor --json — verify project health"
  ]
};
