// GENERATED by apps/docs/scripts/build-cli-manifest.ts — do not edit.
// Rebuild with: bun apps/docs/scripts/build-cli-manifest.ts

export type CliOption = {
  flags: string;
  description: string;
  defaultValue?: unknown;
};

export type CliArgument = {
  name: string;
  required: boolean;
  variadic: boolean;
  description?: string;
};

export type CliCommand = {
  name: string;
  aliases: string[];
  description: string;
  arguments: CliArgument[];
  options: CliOption[];
  subcommands?: CliCommand[];
};

export type CliManifest = {
  cliVersion: string;
  commands: CliCommand[];
  exitCodes: Record<string, string>;
  agentWorkflow: string[];
};

export const CLI_MANIFEST: CliManifest = {
  "cliVersion": "0.1.0",
  "commands": [
    {
      "name": "init",
      "aliases": [],
      "description": "initialize your project and install dependencies",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "names, url or local path to component"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "-y, --yes",
          "description": "skip confirmation prompt.",
          "defaultValue": true
        },
        {
          "flags": "-d, --defaults",
          "description": "use default configuration.",
          "defaultValue": false
        },
        {
          "flags": "-f, --force",
          "description": "force overwrite of existing configuration.",
          "defaultValue": false
        },
        {
          "flags": "-s, --silent",
          "description": "mute output.",
          "defaultValue": false
        },
        {
          "flags": "-b, --base-color <name>",
          "description": "the base color to use."
        },
        {
          "flags": "--css-variables",
          "description": "use css variables for theming.",
          "defaultValue": true
        },
        {
          "flags": "--no-css-variables",
          "description": "do not use css variables for theming."
        }
      ]
    },
    {
      "name": "add",
      "aliases": [],
      "description": "add a component to your project",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "item addresses to add"
        }
      ],
      "options": [
        {
          "flags": "-y, --yes",
          "description": "skip confirmation prompt.",
          "defaultValue": false
        },
        {
          "flags": "-o, --overwrite",
          "description": "overwrite existing files.",
          "defaultValue": false
        },
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "-a, --all",
          "description": "add all available components",
          "defaultValue": false
        },
        {
          "flags": "-p, --path <path>",
          "description": "the path to add the component to."
        },
        {
          "flags": "-s, --silent",
          "description": "mute output.",
          "defaultValue": false
        },
        {
          "flags": "--dry-run",
          "description": "preview changes without writing files.",
          "defaultValue": false
        },
        {
          "flags": "--diff [path]",
          "description": "show diff for a file."
        },
        {
          "flags": "--view [path]",
          "description": "show file contents."
        }
      ]
    },
    {
      "name": "diff",
      "aliases": [],
      "description": "show diffs between local files and their registry versions",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "component names (defaults to all installed)"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "--name-only",
          "description": "only list files that differ.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "docs",
      "aliases": [],
      "description": "print component documentation as markdown",
      "arguments": [
        {
          "name": "components",
          "required": false,
          "variadic": true,
          "description": "component names (e.g. button dialog)"
        }
      ],
      "options": [
        {
          "flags": "-l, --list",
          "description": "list documented components.",
          "defaultValue": false
        },
        {
          "flags": "--json",
          "description": "output as JSON (with --list).",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "show",
      "aliases": [
        "view"
      ],
      "description": "show items from the registry (files, dependencies, source)",
      "arguments": [
        {
          "name": "items",
          "required": true,
          "variadic": true,
          "description": "item addresses to view"
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "--files",
          "description": "only list file paths.",
          "defaultValue": false
        },
        {
          "flags": "--deps",
          "description": "only list npm and registry dependencies.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "search",
      "aliases": [
        "list"
      ],
      "description": "search items from registries",
      "arguments": [
        {
          "name": "registries",
          "required": false,
          "variadic": true,
          "description": "the registry addresses to search. Supports namespaces, GitHub sources and URLs. When omitted, searches all registries configured in components.json."
        }
      ],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "-q, --query <query>",
          "description": "query string"
        },
        {
          "flags": "-t, --type <type>",
          "description": "filter by item type, e.g. ui, block, hook. Comma-separated for multiple."
        },
        {
          "flags": "-l, --limit <number>",
          "description": "maximum number of items to display",
          "defaultValue": "100"
        },
        {
          "flags": "-o, --offset <number>",
          "description": "number of items to skip",
          "defaultValue": "0"
        },
        {
          "flags": "--json",
          "description": "output as JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "status",
      "aliases": [
        "info"
      ],
      "description": "get information about your project",
      "arguments": [],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "--json",
          "description": "output as JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "doctor",
      "aliases": [],
      "description": "check the health of your marko-ui setup",
      "arguments": [],
      "options": [
        {
          "flags": "-c, --cwd <cwd>",
          "description": "the working directory. defaults to the current directory.",
          "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
        },
        {
          "flags": "--json",
          "description": "output as JSON.",
          "defaultValue": false
        }
      ]
    },
    {
      "name": "manifest",
      "aliases": [],
      "description": "print a machine-readable description of the entire CLI",
      "arguments": [],
      "options": []
    },
    {
      "name": "agents",
      "aliases": [],
      "description": "manage generated agent documentation",
      "arguments": [],
      "options": [],
      "subcommands": [
        {
          "name": "sync",
          "aliases": [],
          "description": "generate or refresh AGENTS.md and the marko-ui Claude skill",
          "arguments": [],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
            },
            {
              "flags": "--check",
              "description": "fail (exit 3) if the generated docs are stale.",
              "defaultValue": false
            },
            {
              "flags": "--no-skill",
              "description": "do not write .claude/skills/marko-ui/SKILL.md."
            },
            {
              "flags": "-s, --silent",
              "description": "mute output.",
              "defaultValue": false
            }
          ]
        }
      ]
    },
    {
      "name": "registry",
      "aliases": [],
      "description": "manage registries",
      "arguments": [],
      "options": [],
      "subcommands": [
        {
          "name": "list",
          "aliases": [],
          "description": "list configured registries and the marko-ui registry index",
          "arguments": [],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
            },
            {
              "flags": "--json",
              "description": "output as JSON.",
              "defaultValue": false
            },
            {
              "flags": "--index-only",
              "description": "only show registries from the index.",
              "defaultValue": false
            }
          ]
        },
        {
          "name": "add",
          "aliases": [],
          "description": "add registries to your project",
          "arguments": [
            {
              "name": "registries",
              "required": false,
              "variadic": true,
              "description": "registries (@namespace) or registry URLs (@namespace=url)"
            }
          ],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
            },
            {
              "flags": "-s, --silent",
              "description": "mute output.",
              "defaultValue": false
            }
          ]
        },
        {
          "name": "remove",
          "aliases": [],
          "description": "remove registries from your project",
          "arguments": [
            {
              "name": "registries",
              "required": true,
              "variadic": true,
              "description": "registry namespaces to remove (e.g. @acme)"
            }
          ],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
            },
            {
              "flags": "-s, --silent",
              "description": "mute output.",
              "defaultValue": false
            }
          ]
        },
        {
          "name": "validate",
          "aliases": [],
          "description": "validate a shadcn registry",
          "arguments": [
            {
              "name": "registry",
              "required": false,
              "variadic": false,
              "description": "registry address to validate. Supports registry.json paths and GitHub sources."
            }
          ],
          "options": [
            {
              "flags": "-c, --cwd <cwd>",
              "description": "the working directory. defaults to the current directory.",
              "defaultValue": "/Users/svallory/work/marko-ui/worktrees/cli"
            }
          ]
        }
      ]
    }
  ],
  "exitCodes": {
    "0": "success",
    "1": "operational failure",
    "2": "usage error",
    "3": "doctor/validate found problems",
    "4": "network or registry unreachable"
  },
  "agentWorkflow": [
    "marko-ui search <query> — find items across configured registries",
    "marko-ui view <item> --json — inspect an item's files and dependencies",
    "marko-ui add <item> -y — install it",
    "marko-ui doctor --json — verify project health"
  ]
};
