// SSR-time syntax highlighting via shiki, ported from shadcn/ui's
// lib/highlight-code.ts (apps/v4). shadcn's own code-panel component
// (component-source.tsx — the closest analog to our code-block /
// expandable-code / block-viewer) calls `highlightCode()` directly and
// injects the HTML via dangerouslySetInnerHTML; we do the Marko equivalent
// with `$!{}` inside an `<await>` tag (see call sites).
//
// Why this is a cached SSR-time call and not build-time manifest baking:
// - apps/docs/src/lib/blocks-manifest.ts and src/demos/demos-manifest.ts
//   already inline full raw source as literal TS (generated by
//   scripts/build-blocks-manifest.ts / build-demos-manifest.ts). Baking
//   highlighted HTML into them too would roughly double or triple those
//   files' size (markup + inline shiki color styles per token) for content
//   that's cheap to highlight on demand.
// - Shiki highlighting is CPU-bound but fast per snippet and deterministic,
//   so an in-memory cache keyed by `lang:sha256(code)` makes repeat SSR
//   renders of the same page free after the first hit, without touching the
//   manifest generators at all.
// - Commit 55f21c4 crashed the production container because a module-scope
//   *synchronous* fs.readFileSync ran at boot in code that ships to
//   dist/index.mjs, where the source tree isn't present. Shiki's highlighter
//   creation (getSingletonHighlighter) is async and lazy by design here: it
//   is only ever invoked from inside an async function on first actual use,
//   and the in-flight promise is memoized — never called eagerly at module
//   top-level. This sidesteps that failure mode entirely.
import {
  getSingletonHighlighter,
  type BundledLanguage,
  type Highlighter,
} from "shiki";

// Every language string actually passed by call sites across apps/docs
// (grepped): "marko", "css", "bash", "json", "text", "ts"/"tsx" (docs-content
// snippets), plus "html" for the typeset docs panel's markup-only usage
// snippet. "marko" has a real bundled shiki grammar (verified via shiki's
// own `bundledLanguages` export — dist/langs.mjs ships `marko.mjs`), so we
// use it directly; no html fallback is needed for .marko source itself.
const SUPPORTED_LANGS = [
  "marko",
  "css",
  "bash",
  "json",
  "ts",
  "tsx",
  "html",
] as const satisfies readonly BundledLanguage[];

type SupportedLang = (typeof SUPPORTED_LANGS)[number];

const LANG_ALIASES: Record<string, SupportedLang> = {
  sh: "bash",
  shell: "bash",
  typescript: "ts",
  javascript: "ts",
  js: "ts",
};

const THEMES = { light: "github-light", dark: "github-dark" } as const;

/**
 * Light-theme token colors that fail WCAG 2.2 AA (4.5:1) against the docs
 * code background, remapped to GitHub's own newer `github-light-default`
 * values for the same token roles.
 *
 * Measured on the production build (Lighthouse run 35177842841): these three
 * colors were the ENTIRE cause of the accessibility score sitting at 96/97
 * instead of 100 — `color-contrast` was the only failing audit on all 8
 * audited component pages, and every one of its 73 flagged nodes was a shiki
 * token span carrying one of these three values on the `#fbfbfb` code
 * background:
 *
 *   #22863a  4.47:1  strings / added      -> #116329  7.14:1
 *   #d73a49  4.42:1  keywords / deleted   -> #cf222e  5.18:1
 *   #e36209  3.37:1  constants / params   -> #953800  7.14:1
 *
 * Why remap rather than switch wholesale to `github-light-default`: that
 * theme fixes these three but introduces its own sub-threshold comment gray
 * (#6e7781, 4.39:1), trading three known failures for a new one. Remapping
 * only the failing values keeps the rest of the familiar GitHub palette
 * byte-identical.
 *
 * Lighthouse only ever flagged light mode (every flagged node reported
 * `background color: #fbfbfb`), because it audits the default theme — but
 * dark mode has the same class of defect, and it needed measuring rather
 * than assuming. See DARK_CONTRAST_REMAP.
 */
const LIGHT_CONTRAST_REMAP: Record<string, string> = {
  "#22863a": "#116329",
  "#d73a49": "#cf222e",
  "#e36209": "#953800",
};

/**
 * The same fix for dark mode, which Lighthouse never audits.
 *
 * The docs' dark code background is `--code: var(--surface)` =
 * `oklch(0.2 0 0)` = `#161616` (app.css). Measured against it, 7 of the 8
 * `github-dark` token colors pass comfortably (6.8:1 to 14.2:1) — but the
 * comment gray does not:
 *
 *   #6a737d  3.76:1  comments  -> #7d8590  4.85:1
 *
 * `#7d8590` is GitHub's own newer dark comment color, chosen as the lightest
 * gray that still reads as clearly secondary next to `#e1e4e8` body text
 * (14.2:1) — comments should stay visually muted, just not below the
 * threshold. A brighter gray would pass harder and flatten that hierarchy.
 *
 * (`#24292e` also measures 1.23:1 here, but it is github-dark's own
 * background color, emitted for tokens that paint a background rather than
 * text. It is never used as a foreground on the code surface, so it is not
 * remapped — remapping it would corrupt the few tokens that do use it.)
 */
const DARK_CONTRAST_REMAP: Record<string, string> = {
  "#6a737d": "#7d8590",
};

/**
 * Rewrite shiki's per-token color custom properties through the two remaps.
 *
 * shiki emits `--shiki-light:#RRGGBB;--shiki-dark:#RRGGBB` inline per token
 * (see `defaultColor: false` below), so keying on the property name is
 * precise: each theme's values are remapped independently against its own
 * background, and no other hex in the markup can match the pattern.
 */
function applyContrastRemap(html: string): string {
  return html.replace(
    /--shiki-(light|dark):(#[0-9a-fA-F]{6})/g,
    (whole, theme: string, hex: string) => {
      const remap = theme === "light" ? LIGHT_CONTRAST_REMAP : DARK_CONTRAST_REMAP;
      const mapped = remap[hex.toLowerCase()];
      return mapped ? `--shiki-${theme}:${mapped}` : whole;
    },
  );
}

let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  // Memoized promise, created on first use only — never at module load.
  highlighterPromise ??= getSingletonHighlighter({
    themes: [THEMES.light, THEMES.dark],
    langs: [...SUPPORTED_LANGS],
  });
  return highlighterPromise;
}

function resolveLang(lang: string): SupportedLang | null {
  const normalized = lang.toLowerCase();
  if ((SUPPORTED_LANGS as readonly string[]).includes(normalized)) {
    return normalized as SupportedLang;
  }
  return LANG_ALIASES[normalized] ?? null;
}

function escapeHtml(code: string): string {
  return code
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Plain Map with a max-size eviction instead of pulling in an LRU dependency
// — the working set here (docs snippets + block/demo files) is small and
// stable per deploy, so FIFO eviction once the ceiling is hit is enough.
const CACHE_LIMIT = 500;
const cache = new Map<string, string>();

// FNV-1a (two independent 32-bit passes + length), NOT node:crypto —
// this module is imported at module scope by client-compiled tags
// (code-block, expandable-code, block-viewer...), so it is evaluated in the
// BROWSER bundle too. `import { createHash } from "node:crypto"` there is
// externalized by Vite and THROWS on first access, killing hydration of
// every page that renders a code snippet (all interactivity silently dead;
// found via the behavior suite's 61 keyboard-contract failures). A cache
// key only needs collision resistance across ≤CACHE_LIMIT live entries,
// not cryptographic strength.
function fnv1a(code: string, seed: number): number {
  let hash = seed;
  for (let index = 0; index < code.length; index++) {
    hash ^= code.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

function cacheKey(lang: string, code: string): string {
  return `${lang}:${fnv1a(code, 0x811c9dc5)}:${fnv1a(code, 0x1b873593)}:${code.length}`;
}

/**
 * Highlight `code` as `lang` using shiki's dual-theme mode, returning the
 * inner HTML of a single `<code>` element — one `<span class="line">` per
 * source line, each token span carrying `--shiki-light`/`--shiki-dark` CSS
 * custom properties (see app.css for the rule that picks between them based
 * on the site's own `.dark` class). Callers keep their own `<pre>`/`<code>`
 * wrapper byte-identical (same classes, same id) and inject this via
 * `$!{}` — only the innards change, chrome stays put. Unrecognized
 * languages (including "text") return the plain escaped source, so callers
 * always get a `<code>`-innerHTML-shaped string either way.
 */
export async function highlightCode(
  code: string,
  lang: string,
): Promise<string> {
  const resolved = resolveLang(lang);
  if (!resolved) {
    return escapeHtml(code);
  }

  const key = cacheKey(resolved, code);
  const cached = cache.get(key);
  if (cached) return cached;

  const highlighter = await getHighlighter();
  const html = highlighter.codeToHtml(code, {
    lang: resolved,
    themes: THEMES,
    // Required so shiki emits BOTH --shiki-light and --shiki-dark vars per
    // span instead of eagerly picking one theme's color as the default —
    // verified empirically: omitting this collapses to a single resolved
    // `color` per span rather than the two CSS custom properties our
    // dark-mode CSS switches between.
    defaultColor: false,
  });

  // Extract just the <code>...</code> inner HTML from shiki's <pre><code>
  // output — cheap string slicing beats parsing the HAST tree a second time
  // for a shape this predictable (shiki always emits exactly one root
  // <pre><code>...</code></pre>).
  const codeStart = html.indexOf("<code");
  const codeOpenEnd = html.indexOf(">", codeStart) + 1;
  const codeEnd = html.lastIndexOf("</code>");
  // Remap before caching so the contrast fix is applied exactly once per
  // snippet and every cache hit serves the corrected markup.
  const inner = applyContrastRemap(html.slice(codeOpenEnd, codeEnd));

  if (cache.size >= CACHE_LIMIT) {
    const oldestKey = cache.keys().next().value;
    if (oldestKey !== undefined) cache.delete(oldestKey);
  }
  cache.set(key, inner);

  return inner;
}

/** Map a manifest file's target path extension to a highlight-code lang. */
export function langFromFilename(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() ?? "";
  switch (ext) {
    case "marko":
      return "marko";
    case "ts":
      return "ts";
    case "tsx":
      return "tsx";
    case "css":
      return "css";
    case "json":
      return "json";
    default:
      return "text";
  }
}

/**
 * Highlight every file in a manifest's file list once, keyed by its `target`
 * path. Built for block-viewer.marko: its file-tree switches the active file
 * entirely client-side after hydration, and Marko's `<await>` tag does not
 * re-resolve when a later reactive update produces a new promise for the
 * same expression (verified empirically — see that template's header
 * comment). Resolving every file's HTML once up front, keyed by target, lets
 * the template do a synchronous, ordinarily-reactive lookup on file-switch
 * instead of re-awaiting per click.
 */
export async function highlightManifestFiles(
  files: readonly { target: string; content: string }[],
): Promise<Record<string, string>> {
  const entries = await Promise.all(
    files.map(async (file) => {
      const html = await highlightCode(file.content, langFromFilename(file.target));
      return [file.target, html] as const;
    }),
  );
  return Object.fromEntries(entries);
}
