// SSR-time syntax highlighting via shiki, ported from shadcn/ui's
// lib/highlight-code.ts (apps/v4). shadcn's own code-panel component
// (component-source.tsx — the closest analog to our code-block /
// expandable-code / block-viewer) calls `highlightCode()` directly and
// injects the HTML via dangerouslySetInnerHTML; we do the Marko equivalent
// with `$!{}` inside an `<await>` tag (see call sites).
//
// Why this is a cached SSR-time call and not build-time manifest baking:
// - apps/docs/src/lib/blocks-manifest.ts and src/demos/demos-manifest.ts
//   already inline full raw source as literal TS (generated by
//   scripts/build-blocks-manifest.ts / build-demos-manifest.ts). Baking
//   highlighted HTML into them too would roughly double or triple those
//   files' size (markup + inline shiki color styles per token) for content
//   that's cheap to highlight on demand.
// - Shiki highlighting is CPU-bound but fast per snippet and deterministic,
//   so an in-memory cache keyed by `lang:sha256(code)` makes repeat SSR
//   renders of the same page free after the first hit, without touching the
//   manifest generators at all.
// - Commit 55f21c4 crashed the production container because a module-scope
//   *synchronous* fs.readFileSync ran at boot in code that ships to
//   dist/index.mjs, where the source tree isn't present. Shiki's highlighter
//   creation (getSingletonHighlighter) is async and lazy by design here: it
//   is only ever invoked from inside an async function on first actual use,
//   and the in-flight promise is memoized — never called eagerly at module
//   top-level. This sidesteps that failure mode entirely.
import {
  getSingletonHighlighter,
  type BundledLanguage,
  type Highlighter,
} from "shiki";

// Every language string actually passed by call sites across apps/docs
// (grepped): "marko", "css", "bash", "json", "text", "ts"/"tsx" (docs-content
// snippets), plus "html" for the typeset docs panel's markup-only usage
// snippet. "marko" has a real bundled shiki grammar (verified via shiki's
// own `bundledLanguages` export — dist/langs.mjs ships `marko.mjs`), so we
// use it directly; no html fallback is needed for .marko source itself.
const SUPPORTED_LANGS = [
  "marko",
  "css",
  "bash",
  "json",
  "ts",
  "tsx",
  "html",
] as const satisfies readonly BundledLanguage[];

type SupportedLang = (typeof SUPPORTED_LANGS)[number];

const LANG_ALIASES: Record<string, SupportedLang> = {
  sh: "bash",
  shell: "bash",
  typescript: "ts",
  javascript: "ts",
  js: "ts",
};

const THEMES = { light: "github-light", dark: "github-dark" } as const;

let highlighterPromise: Promise<Highlighter> | null = null;

function getHighlighter(): Promise<Highlighter> {
  // Memoized promise, created on first use only — never at module load.
  highlighterPromise ??= getSingletonHighlighter({
    themes: [THEMES.light, THEMES.dark],
    langs: [...SUPPORTED_LANGS],
  });
  return highlighterPromise;
}

function resolveLang(lang: string): SupportedLang | null {
  const normalized = lang.toLowerCase();
  if ((SUPPORTED_LANGS as readonly string[]).includes(normalized)) {
    return normalized as SupportedLang;
  }
  return LANG_ALIASES[normalized] ?? null;
}

function escapeHtml(code: string): string {
  return code
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

// Plain Map with a max-size eviction instead of pulling in an LRU dependency
// — the working set here (docs snippets + block/demo files) is small and
// stable per deploy, so FIFO eviction once the ceiling is hit is enough.
const CACHE_LIMIT = 500;
const cache = new Map<string, string>();

// FNV-1a (two independent 32-bit passes + length), NOT node:crypto —
// this module is imported at module scope by client-compiled tags
// (code-block, expandable-code, block-viewer...), so it is evaluated in the
// BROWSER bundle too. `import { createHash } from "node:crypto"` there is
// externalized by Vite and THROWS on first access, killing hydration of
// every page that renders a code snippet (all interactivity silently dead;
// found via the behavior suite's 61 keyboard-contract failures). A cache
// key only needs collision resistance across ≤CACHE_LIMIT live entries,
// not cryptographic strength.
function fnv1a(code: string, seed: number): number {
  let hash = seed;
  for (let index = 0; index < code.length; index++) {
    hash ^= code.charCodeAt(index);
    hash = Math.imul(hash, 0x01000193);
  }
  return hash >>> 0;
}

function cacheKey(lang: string, code: string): string {
  return `${lang}:${fnv1a(code, 0x811c9dc5)}:${fnv1a(code, 0x1b873593)}:${code.length}`;
}

/**
 * Highlight `code` as `lang` using shiki's dual-theme mode, returning the
 * inner HTML of a single `<code>` element — one `<span class="line">` per
 * source line, each token span carrying `--shiki-light`/`--shiki-dark` CSS
 * custom properties (see app.css for the rule that picks between them based
 * on the site's own `.dark` class). Callers keep their own `<pre>`/`<code>`
 * wrapper byte-identical (same classes, same id) and inject this via
 * `$!{}` — only the innards change, chrome stays put. Unrecognized
 * languages (including "text") return the plain escaped source, so callers
 * always get a `<code>`-innerHTML-shaped string either way.
 */
export async function highlightCode(
  code: string,
  lang: string,
): Promise<string> {
  const resolved = resolveLang(lang);
  if (!resolved) {
    return escapeHtml(code);
  }

  const key = cacheKey(resolved, code);
  const cached = cache.get(key);
  if (cached) return cached;

  const highlighter = await getHighlighter();
  const html = highlighter.codeToHtml(code, {
    lang: resolved,
    themes: THEMES,
    // Required so shiki emits BOTH --shiki-light and --shiki-dark vars per
    // span instead of eagerly picking one theme's color as the default —
    // verified empirically: omitting this collapses to a single resolved
    // `color` per span rather than the two CSS custom properties our
    // dark-mode CSS switches between.
    defaultColor: false,
  });

  // Extract just the <code>...</code> inner HTML from shiki's <pre><code>
  // output — cheap string slicing beats parsing the HAST tree a second time
  // for a shape this predictable (shiki always emits exactly one root
  // <pre><code>...</code></pre>).
  const codeStart = html.indexOf("<code");
  const codeOpenEnd = html.indexOf(">", codeStart) + 1;
  const codeEnd = html.lastIndexOf("</code>");
  const inner = html.slice(codeOpenEnd, codeEnd);

  if (cache.size >= CACHE_LIMIT) {
    const oldestKey = cache.keys().next().value;
    if (oldestKey !== undefined) cache.delete(oldestKey);
  }
  cache.set(key, inner);

  return inner;
}

/** Map a manifest file's target path extension to a highlight-code lang. */
export function langFromFilename(filename: string): string {
  const ext = filename.split(".").pop()?.toLowerCase() ?? "";
  switch (ext) {
    case "marko":
      return "marko";
    case "ts":
      return "ts";
    case "tsx":
      return "tsx";
    case "css":
      return "css";
    case "json":
      return "json";
    default:
      return "text";
  }
}

/**
 * Highlight every file in a manifest's file list once, keyed by its `target`
 * path. Built for block-viewer.marko: its file-tree switches the active file
 * entirely client-side after hydration, and Marko's `<await>` tag does not
 * re-resolve when a later reactive update produces a new promise for the
 * same expression (verified empirically — see that template's header
 * comment). Resolving every file's HTML once up front, keyed by target, lets
 * the template do a synchronous, ordinarily-reactive lookup on file-switch
 * instead of re-awaiting per click.
 */
export async function highlightManifestFiles(
  files: readonly { target: string; content: string }[],
): Promise<Record<string, string>> {
  const entries = await Promise.all(
    files.map(async (file) => {
      const html = await highlightCode(file.content, langFromFilename(file.target));
      return [file.target, html] as const;
    }),
  );
  return Object.fromEntries(entries);
}
